pub fn generate_header_code(main_js: &str, stable_storage_js: &str) -> proc_macro2::TokenStream {
    quote::quote! {
        // This code is automatically generated by Azle

        #![allow(warnings, unused)]

        use std::str::FromStr;
        use azle_vm_value_derive::{
            CdkActTryIntoVmValue,
            CdkActTryFromVmValue
        };
        use ic_cdk::api::call::CallResult;
        use std::borrow::BorrowMut;
        use rand::{
            Rng,
            SeedableRng,
            rngs::StdRng
        };

        thread_local! {
            static BOA_CONTEXT_REF_CELL: std::cell::RefCell<boa_engine::Context> = std::cell::RefCell::new(boa_engine::Context::default());
        }

        static MAIN_JS: &'static str = #main_js;
        static STABLE_STORAGE_JS: &'static str = #stable_storage_js;
    }
}
