pub fn generate_header_code() -> proc_macro2::TokenStream {
    quote::quote! {
        // This code is automatically generated by Azle

        // #![allow(dead_code)]
        // #![allow(non_camel_case_types)]
        // #![allow(non_snake_case)]
        // #![allow(unused_imports)]
        // #![allow(unused_variables)]
        #![allow(warnings, unused)]

        use std::str::FromStr;
        use azle_vm_value_derive::{
            CdkActTryIntoVmValue,
            CdkActTryFromVmValue
        };
        use ic_cdk::api::call::CallResult;
        use std::borrow::BorrowMut;
        use rand::{
            Rng,
            SeedableRng,
            rngs::StdRng
        };
    }
}
