
        // This code is automatically generated by Azle

        fn custom_getrandom(_buf: &mut [u8]) -> Result<(), getrandom::Error> { Ok(()) }

        getrandom::register_custom_getrandom!(custom_getrandom);
        
        
        #[ic_cdk_macros::query]
        fn echo(message: String) -> String {
            let mut context = boa::Context::new();
        
            let return_value = context.eval(format!(
                "
                    {compiled_js}

                    echo(\"{message}\");
                ",
                compiled_js = "function echo(message) {
    return message;
}
",
                message = message
            )).unwrap();
        
            ic_cdk::println!("return_value: {:#?}", return_value);

            return_value.as_string().unwrap().to_string()
        }
    
    