import { describe } from '@jest/globals';
import { please, Test } from 'azle/test/jest';
import { execSync } from 'child_process';
import { rm } from 'fs-extra';
import { join } from 'path';

import { Unit } from '../../../scripts/file_generator';
import { generateTestFileOfSize } from './generate_test_files';
import { getAutoGeneratedFileName, verifyUpload } from './tests';

const hugeAutoGenAutoUploadFileInfos: [number, Unit][] = [[2, 'GiB']];

export function hugeFilesTests(origin: string): Test {
    return () => {
        please(
            'remove all other auto generated files so there is room for huge files',
            async () => {
                await rm(join('assets', 'auto'), {
                    recursive: true,
                    force: true
                });
            }
        );

        describe.each(hugeAutoGenAutoUploadFileInfos)(
            'generate huge files',
            (size, units) => {
                const fileName = getAutoGeneratedFileName(size, units);
                please(
                    `generate huge file: ${fileName}`,
                    async () => {
                        await generateTestFileOfSize(size, units);
                    },
                    10 * 60 * 1_000
                );
            }
        );

        please(
            'redeploy the canister to remove files and reupload',
            async () => {
                execSync(`dfx deploy --upgrade-unchanged`, {
                    stdio: 'inherit'
                });
            }
        );

        describe.each(hugeAutoGenAutoUploadFileInfos)(
            'verify huge files were uploaded correctly',
            (size, units) => {
                const fileName = getAutoGeneratedFileName(size, units);
                verifyUpload(origin, join('auto', fileName), fileName);
            }
        );
    };
}
