[bans]
[bans.workspace-dependencies]
unused = "deny"

[licenses]
allow = [
    "MIT",
    "Apache-2.0",
    "ISC",
    "Zlib",
    "CC0-1.0",
    "MPL-2.0", # TODO try and remove when we replace wasmedge_quickjs
    "Unicode-3.0"
]

[sources]
allow-git = [
    "https://github.com/demergent-labs/wasmedge-quickjs",
    "https://github.com/demergent-labs/candid",
]
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
unknown-registry = "deny"

[advisories]
yanked = "deny"
unmaintained = "all"
ignore = [
    # encoding crate is unmaintained but used by wasmedge_quickjs
    # Alternative: encoding_rs, but would require upstream changes
    "RUSTSEC-2021-0153",

    # paste crate is no longer maintained but used by candid
    # This is a transitive dependency from IC SDK
    "RUSTSEC-2024-0436",
]
