[bans]
# This section is considered when running `cargo deny check bans`

[bans.workspace-dependencies]

unused = "deny"

[licenses]
# This section is considered when running `cargo deny check licenses`

allow = [
    "MIT",
    "Apache-2.0",
    "ISC",
    "Zlib",
    "CC0-1.0",
    "MPL-2.0", # TODO try and remove when we replace wasmedge_quickjs
    "Unicode-3.0"
]

[sources]
# This section is considered when running `cargo deny check sources`

# List of URLs for allowed Git repositories
allow-git = [
    "https://github.com/demergent-labs/wasmedge-quickjs",
    "https://github.com/demergent-labs/candid",
]

# Explicitly deny unknown git sources (strictest setting)
unknown-git = "deny"

# Explicitly deny unknown registries (only allow crates.io)
unknown-registry = "deny"

# Allow only crates.io registry
allow-registry = ["https://github.com/rust-lang/crates.io-index"]

[advisories]
# This section is considered when running `cargo deny check advisories`

# Deny yanked crates (strictest setting)
yanked = "deny"

# Deny unmaintained crates - valid values: "all", "workspace", "transitive", "none"
# "all" = strictest, fails for any unmaintained dependency
unmaintained = "all"

# Ignore specific advisories by their ID (minimize this list!)
ignore = [
    # encoding crate is unmaintained but used by wasmedge_quickjs
    # Alternative: encoding_rs, but would require upstream changes
    "RUSTSEC-2021-0153",

    # paste crate is no longer maintained but used by candid
    # This is a transitive dependency from IC SDK
    "RUSTSEC-2024-0436",
]
