[licenses]
# This section is considered when running `cargo deny check licenses`

allow = [
    "MIT",
    "Apache-2.0",
    "ISC",
    "Zlib",
    "CC0-1.0",
    "MPL-2.0",
    "Unicode-3.0"
]

[bans]
# This section is considered when running `cargo deny check bans`

# Deny multiple versions of the same dependency
multiple-versions = "warn"

# Configure workspace dependency checking
[bans.workspace-dependencies]
# Warn when a workspace dependency is not used
unused = "warn"

[sources]
# This section is considered when running `cargo deny check sources`

# List of URLs for allowed Git repositories
allow-git = [
    "https://github.com/demergent-labs/wasmedge-quickjs",
    "https://github.com/demergent-labs/candid",
]

[advisories]
# This section is considered when running `cargo deny check advisories`

# Ignore specific advisories by their ID
ignore = [
    # encoding crate is unmaintained but used by wasmedge_quickjs
    # Alternative: encoding_rs, but would require upstream changes
    "RUSTSEC-2021-0153",

    # paste crate is no longer maintained but used by candid
    # This is a transitive dependency from IC SDK
    "RUSTSEC-2024-0436",
]
