name: 'Determine workflow config'
description: 'Determines the workflow configuration based on the current GitHub context'

inputs:
    is-workflow-dispatch:
        description: 'Whether this is a workflow dispatch event'
        required: true
    exclude-slow-dispatch-input-value:
        description: 'Workflow dispatch input for excluding slow tests'
        required: true
    exclude-unstable-dispatch-input-value:
        description: 'Workflow dispatch input for excluding unstable tests'
        required: true
    exclude-release-only-dispatch-input-value:
        description: 'Workflow dispatch input for excluding release-only tests'
        required: true
    fuzz-dispatch-input-value:
        description: 'Workflow dispatch input for running fuzz tests'
        required: false
        default: 'false'
    link-azle-dispatch-input-value:
        description: 'Workflow dispatch input for linking to the development version of azle'
        required: true

outputs:
    exclude-slow:
        description: 'Whether to exclude slow tests'
        value: ${{ steps.determine_workflow_config.outputs.exclude-slow }}
    exclude-unstable:
        description: 'Whether to exclude unstable tests'
        value: ${{ steps.determine_workflow_config.outputs.exclude-unstable }}
    exclude-release-only:
        description: 'Whether to exclude release-only tests'
        value: ${{ steps.determine_workflow_config.outputs.exclude-release-only }}
    link-azle:
        description: 'Whether to link to the development version of azle'
        value: ${{ steps.determine_workflow_config.outputs.link-azle }}
    fuzz:
        description: 'Whether to run fuzz tests'
        value: ${{ steps.determine_workflow_config.outputs.fuzz }}
    is-dependabot:
        description: 'Whether the commit is from Dependabot'
        value: ${{ steps.determine_workflow_config.outputs.is-dependabot }}

runs:
    using: 'composite'
    steps:
        - id: workflow-context
          uses: ./.github/actions/determine_workflow_context

        - id: determine_workflow_config
          shell: bash
          run: |
              if [[ "${{ inputs.is-workflow-dispatch }}" == "true" ]]; then
                echo "exclude-slow=${{ inputs.exclude-slow-dispatch-input-value }}" >> $GITHUB_OUTPUT
                echo "exclude-unstable=${{ inputs.exclude-unstable-dispatch-input-value }}" >> $GITHUB_OUTPUT
                echo "exclude-release-only=${{ inputs.exclude-release-only-dispatch-input-value }}" >> $GITHUB_OUTPUT
                echo "link-azle=${{ inputs.link-azle-dispatch-input-value }}" >> $GITHUB_OUTPUT
                echo "fuzz=${{ inputs.fuzz-dispatch-input-value }}" >> $GITHUB_OUTPUT
                echo "is-dependabot=false" >> $GITHUB_OUTPUT
              else
                EXCLUDE_SLOW=${{ steps.workflow-context.outputs.is_feature_branch_draft_pr == 'true' }}
                EXCLUDE_UNSTABLE=${{ steps.workflow-context.outputs.is_feature_branch_draft_pr == 'true' || steps.workflow-context.outputs.is_feature_branch_pr == 'true' || steps.workflow-context.outputs.is_main_branch_push == 'true' }}
                EXCLUDE_RELEASE_ONLY=${{ steps.workflow-context.outputs.is_feature_branch_draft_pr == 'true' || steps.workflow-context.outputs.is_feature_branch_pr == 'true' || steps.workflow-context.outputs.is_main_branch_push == 'true' }}

                echo "exclude-slow=$EXCLUDE_SLOW" >> $GITHUB_OUTPUT
                echo "exclude-unstable=$EXCLUDE_UNSTABLE" >> $GITHUB_OUTPUT
                echo "exclude-release-only=$EXCLUDE_RELEASE_ONLY" >> $GITHUB_OUTPUT
                if [[ "${{ steps.workflow-context.outputs.is_main_branch_push_from_release_merge }}" == "true" || \
                      "${{ steps.workflow-context.outputs.is_release_branch_pr }}" == "true" ]]; then
                  echo "link-azle=false" >> $GITHUB_OUTPUT
                else
                  echo "link-azle=true" >> $GITHUB_OUTPUT
                fi
                echo "fuzz=false" >> $GITHUB_OUTPUT
                echo ${{ github.actor }}
                echo "is-dependabot=${{ github.actor == 'dependabot[bot]' }}" >> $GITHUB_OUTPUT
              fi

        - id: echo-outputs
          shell: bash
          run: |
              echo "Test Conditions Outputs:"
              echo "exclude-slow: ${{ steps.determine_workflow_config.outputs.exclude-slow }}"
              echo "exclude-unstable: ${{ steps.determine_workflow_config.outputs.exclude-unstable }}"
              echo "exclude-release-only: ${{ steps.determine_workflow_config.outputs.exclude-release-only }}"
              echo "link-azle: ${{ steps.determine_workflow_config.outputs.link-azle }}"
              echo "fuzz: ${{ steps.determine_workflow_config.outputs.fuzz }}"
              echo "is-dependabot: ${{ steps.determine_workflow_config.outputs.is-dependabot }}"
