name: Get dfx version
description: Determines Azle's dfx version
outputs:
    dfx-version:
        description: Returns the version of dfx Azle used for it's last template
        value: ${{ steps.get-dfx-version.outputs.dfx-version }}
runs:
    using: composite
    steps:
        - uses: actions/checkout@v4

        - id: get-dfx-version
          run: |
              DFX_VERSION=$(./.github/actions/get_dfx_version/get_dfx_version.sh)
              echo "dfx-version=${DFX_VERSION}" >> "$GITHUB_OUTPUT"
          shell: bash
