mod timers;

pub fn generate_header_code() -> proc_macro2::TokenStream {
    let timers_module = timers::generate_timers_module();

    quote::quote! {
        // This code is automatically generated by Azle

        // #![allow(dead_code)]
        // #![allow(non_camel_case_types)]
        // #![allow(non_snake_case)]
        // #![allow(unused_imports)]
        // #![allow(unused_variables)]
        #![allow(warnings, unused)]

        use azle_vm_value_derive::{CdkActTryIntoVmValue, CdkActTryFromVmValue};
        use ic_cdk::api::call::CallResult;
        use rand::Rng;
        use slotmap::Key;
        use std::str::FromStr;

        thread_local! {
            static RNG_REF_CELL: std::cell::RefCell<rand::rngs::StdRng> = std::cell::RefCell::new(rand::SeedableRng::from_seed([0u8; 32]));
        }

        #timers_module
    }
}
