mod ref_cells;
mod use_statements;

pub fn generate_header(main_js: &str) -> proc_macro2::TokenStream {
    let use_statements = use_statements::generate_use_statements();
    let ref_cells = ref_cells::generate_ref_cells();

    quote::quote! {
        // This code is automatically generated by Azle

        #![allow(warnings, unused)]

        #use_statements

        #ref_cells

        static MAIN_JS: &'static str = #main_js;
    }
}
