import { Rust } from '../../../types';

export function generateHead(): Rust {
    return `
        // This code is automatically generated by Azle

        #![allow(dead_code)]
        #![allow(non_camel_case_types)]
        #![allow(non_snake_case)]
        #![allow(unused_imports)]
        #![allow(unused_variables)]

        thread_local! {
            static BOA_CONTEXT: std::cell::RefCell<boa_engine::Context> = std::cell::RefCell::new(boa_engine::Context::default());
        }

        fn custom_getrandom(_buf: &mut [u8]) -> Result<(), getrandom::Error> { Ok(()) }

        getrandom::register_custom_getrandom!(custom_getrandom);
    `;
}