name: Configure Git
description: 'Configures git with azle-bot user info'
runs:
    using: composite
    steps:
        - name: Configure git
          run: |
              git config --global user.name 'azle-bot[bot]'
              if [[ -n "$AZLE_BOT_ID" ]]; then
                  git config --global user.email "${AZLE_BOT_ID}+azle-bot[bot]@users.noreply.github.com"
              else
                  git config --global user.email 'azle-bot[bot]@users.noreply.github.com'
              fi
          shell: bash
