name: Configure Git
description: 'Configures git with azle-bot user info'
runs:
    using: composite
    steps:
        - name: Configure git
          run: |
              git config --global user.name 'azle-bot[bot]'
              git config --global user.email 'azle-bot[bot]@users.noreply.github.com'
          shell: bash
