# TODO I feel like the wording on this is a little clunky and/or ethereal.
# TODO we have is release vs should release and I don't feel like it's clear what the answer is
name: Should release
description: Determines if the current pull request is for testing or for starting a release
outputs:
    should_release:
        description: Returns true if this branch should start a release, otherwise false
        value: ${{ steps.determine_should_release.outputs.should_release }}
runs:
    using: composite
    steps:
        - uses: actions/checkout@v4
          with:
              ref: ${{ github.event.pull_request.head.ref }} # This is necessary for this job to be able to get the correct commit message from `git log`

        - id: determine_should_release
          run: |
              BRANCH_NAME="${{ github.head_ref }}"
              RELEASE_VERSION="${BRANCH_NAME:9}"
              COMMIT_MESSAGE=$(git log -1 --pretty=format:"%s")
              IS_RELEASE_BRANCH_PR="${{ contains(github.head_ref, 'release--') }}"

              SHOULD_RELEASE="false"
              if [[ $IS_RELEASE_BRANCH_PR == "true" && "$COMMIT_MESSAGE" != "azle-bot automated release $RELEASE_VERSION" ]]; then
                  SHOULD_RELEASE="true"
              fi

              echo "should_release=${SHOULD_RELEASE}" >> "$GITHUB_OUTPUT"
          shell: bash
