name: Cool

on:
    pull_request:
        types:
            - opened
            - synchronize
            - ready_for_review
            - reopened
    workflow_dispatch:
        inputs:
            fuzz:
                description: 'Run fuzz tests'
                required: true
                type: boolean
                default: false

jobs:
    do-cool-stuff:
        name: Do cool stuff
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - run: echo "Hello, world!"
