import { OptLevel, Toml } from '../../utils/types';

export function generateWorkspaceCargoToml(
    rootPath: string,
    optLevel: OptLevel
): Toml {
    const optLevels = {
        '0': `opt-level = 'z'`,
        '1': `
            opt-level = 'z'
            lto = "thin"
        `,
        '2': `
            opt-level = 'z'
            lto = "thin"
            codegen-units = 1
        `,
        '3': `
            opt-level = 'z'
            lto = "fat"
        `,
        '4': `
            opt-level = 'z'
            lto = "fat"
            codegen-units = 1
        `
    };

    return `
        # This code is automatically generated by Azle

        [workspace]
        members = [
            "${rootPath}",
            "${rootPath}/azle_generate"
        ]

        [profile.release]
        ${optLevels[optLevel]}
    `;
}

export function generateLibCargoToml(
    canisterName: string,
    pluginsDependencies: string
): Toml {
    return `
        # This code is automatically generated by Azle

        [package]
        name = "${canisterName}"
        version = "0.0.0"
        edition = "2018"

        [lib]
        crate-type = ["cdylib"]

        [dependencies]
        ic-cdk = "=0.8.0-beta.0"
        ic-cdk-macros = "=0.6.10"
        ic-cdk-timers = "=0.1.2"
        ic-stable-structures = "=0.5.2"
        candid = { version = "=0.9.0-beta.3", features = ["parser"] }
        boa_engine = { git = "https://github.com/boa-dev/boa", rev = "08a72387ba5cd185f657e98d984ff2ce328da69e" }
        # boa_engine = { git = "https://github.com/demergent-labs/boa", rev = "2613202fdc2757691ba1a20e568e5b8740e0c233" }
        # boa_engine = { path = "/home/boa/boa_engine" }
        getrandom = { version = "=0.2.3", features = ["custom"] }
        chrono = { version = "=0.4.24", default-features = false }
        serde = "1.0.137"
        azle-vm-value-derive = { path = "./azle_vm_value_derive" }
        uuid = { version = "=1.2.2", features = ["v4"] }
        rand = "=0.8.5"
        slotmap = "=1.0.6"

        ${pluginsDependencies}
    `;
}

export function generateWorkspaceCargoLock(): Toml {
    return `
        # This file is automatically @generated by Cargo.
        # It is not intended for manual editing.
        version = 3
        
        [[package]]
        name = "Inflector"
        version = "0.11.4"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "fe438c63458706e03479442743baae6c88256498e6431708f6dfc520a26515d3"
        dependencies = [
        "lazy_static",
        "regex",
        ]
        
        [[package]]
        name = "ahash"
        version = "0.7.6"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "fcb51a0695d8f838b1ee009b3fbf66bda078cd64590202a864a8f3e8c4315c47"
        dependencies = [
        "getrandom",
        "once_cell",
        "version_check",
        ]
        
        [[package]]
        name = "ahash"
        version = "0.8.3"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "2c99f64d1e06488f620f932677e24bc6e2897582980441ae90a671415bd7ec2f"
        dependencies = [
        "cfg-if",
        "once_cell",
        "version_check",
        ]
        
        [[package]]
        name = "aho-corasick"
        version = "1.0.1"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "67fc08ce920c31afb70f013dcce1bfc3a3195de6a228474e45e1f145b36f8d04"
        dependencies = [
        "memchr",
        ]
        
        [[package]]
        name = "android_system_properties"
        version = "0.1.5"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "819e7219dbd41043ac279b19830f2efc897156490d7fd6ea916720117ee66311"
        dependencies = [
        "libc",
        ]
        
        [[package]]
        name = "annotate-snippets"
        version = "0.9.1"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "c3b9d411ecbaf79885c6df4d75fff75858d5995ff25385657a28af47e82f9c36"
        dependencies = [
        "unicode-width",
        ]
        
        [[package]]
        name = "anyhow"
        version = "1.0.71"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "9c7d0618f0e0b7e8ff11427422b64564d5fb0be1940354bfe2e0529b18a9d9b8"
        
        [[package]]
        name = "arrayvec"
        version = "0.5.2"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "23b62fc65de8e4e7f52534fb52b0f3ed04746ae267519eef2a83941e8085068b"
        
        [[package]]
        name = "ascii-canvas"
        version = "3.0.0"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "8824ecca2e851cec16968d54a01dd372ef8f95b244fb84b84e70128be347c3c6"
        dependencies = [
        "term",
        ]
        
        [[package]]
        name = "ast_node"
        version = "0.8.8"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "70151a5226578411132d798aa248df45b30aa34aea2e580628870b4d87be717b"
        dependencies = [
        "darling",
        "pmutil",
        "proc-macro2",
        "quote",
        "swc_macros_common",
        "syn 1.0.109",
        ]
        
        [[package]]
        name = "atomic-polyfill"
        version = "1.0.2"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "c314e70d181aa6053b26e3f7fbf86d1dfff84f816a6175b967666b3506ef7289"
        dependencies = [
        "critical-section",
        ]
        
        [[package]]
        name = "autocfg"
        version = "1.1.0"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "d468802bab17cbc0cc575e9b053f41e72aa36bfa6b7f55e3529ffa43161b97fa"
        
        [[package]]
        name = "azle-vm-value-derive"
        version = "0.0.0"
        dependencies = [
        "proc-macro2",
        "quote",
        "syn 1.0.109",
        ]
        
        [[package]]
        name = "azle_generate"
        version = "0.0.0"
        dependencies = [
        "annotate-snippets",
        "cdk_framework",
        "prettyplease",
        "proc-macro2",
        "quote",
        "serde",
        "serde_json",
        "swc_common",
        "swc_ecma_ast",
        "swc_ecma_parser",
        "syn 2.0.15",
        ]
        
        [[package]]
        name = "beef"
        version = "0.5.2"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "3a8241f3ebb85c056b509d4327ad0358fbbba6ffb340bf388f26350aeda225b1"
        
        [[package]]
        name = "better_scoped_tls"
        version = "0.1.0"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "b73e8ecdec39e98aa3b19e8cd0b8ed8f77ccb86a6b0b2dc7cd86d105438a2123"
        dependencies = [
        "scoped-tls",
        ]
        
        [[package]]
        name = "binread"
        version = "2.2.0"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "16598dfc8e6578e9b597d9910ba2e73618385dc9f4b1d43dd92c349d6be6418f"
        dependencies = [
        "binread_derive",
        "lazy_static",
        "rustversion",
        ]
        
        [[package]]
        name = "binread_derive"
        version = "2.1.0"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "1d9672209df1714ee804b1f4d4f68c8eb2a90b1f7a07acf472f88ce198ef1fed"
        dependencies = [
        "either",
        "proc-macro2",
        "quote",
        "syn 1.0.109",
        ]
        
        [[package]]
        name = "bit-set"
        version = "0.5.3"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "0700ddab506f33b20a03b13996eccd309a48e5ff77d0d95926aa0210fb4e95f1"
        dependencies = [
        "bit-vec",
        ]
        
        [[package]]
        name = "bit-vec"
        version = "0.6.3"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "349f9b6a179ed607305526ca489b34ad0a41aed5f7980fa90eb03160b69598fb"
        
        [[package]]
        name = "bitflags"
        version = "1.3.2"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "bef38d45163c2f1dde094a7dfd33ccf595c92905c8f8f4fdc18d06fb1037718a"
        
        [[package]]
        name = "bitflags"
        version = "2.2.1"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "24a6904aef64d73cf10ab17ebace7befb918b82164785cb89907993be7f83813"
        
        [[package]]
        name = "block-buffer"
        version = "0.10.4"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "3078c7629b62d3f0439517fa394996acacc5cbc91c5a20d8c658e77abd503a71"
        dependencies = [
        "generic-array",
        ]
        
        [[package]]
        name = "boa_ast"
        version = "0.16.0"
        source = "git+https://github.com/boa-dev/boa?rev=08a72387ba5cd185f657e98d984ff2ce328da69e#08a72387ba5cd185f657e98d984ff2ce328da69e"
        dependencies = [
        "bitflags 2.2.1",
        "boa_interner",
        "boa_macros",
        "num-bigint",
        "rustc-hash",
        ]
        
        [[package]]
        name = "boa_engine"
        version = "0.16.0"
        source = "git+https://github.com/boa-dev/boa?rev=08a72387ba5cd185f657e98d984ff2ce328da69e#08a72387ba5cd185f657e98d984ff2ce328da69e"
        dependencies = [
        "bitflags 2.2.1",
        "boa_ast",
        "boa_gc",
        "boa_icu_provider",
        "boa_interner",
        "boa_macros",
        "boa_parser",
        "boa_profiler",
        "chrono",
        "dashmap",
        "fast-float",
        "icu_normalizer",
        "indexmap",
        "itertools",
        "num-bigint",
        "num-integer",
        "num-traits",
        "num_enum 0.6.1",
        "once_cell",
        "pollster",
        "rand",
        "regress",
        "rustc-hash",
        "ryu-js",
        "serde",
        "serde_json",
        "sptr",
        "static_assertions",
        "tap",
        "thin-vec",
        "thiserror",
        ]
        
        [[package]]
        name = "boa_gc"
        version = "0.16.0"
        source = "git+https://github.com/boa-dev/boa?rev=08a72387ba5cd185f657e98d984ff2ce328da69e#08a72387ba5cd185f657e98d984ff2ce328da69e"
        dependencies = [
        "boa_macros",
        "boa_profiler",
        "thin-vec",
        ]
        
        [[package]]
        name = "boa_icu_provider"
        version = "0.16.0"
        source = "git+https://github.com/boa-dev/boa?rev=08a72387ba5cd185f657e98d984ff2ce328da69e#08a72387ba5cd185f657e98d984ff2ce328da69e"
        dependencies = [
        "icu_collections",
        "icu_normalizer",
        "icu_properties",
        "icu_provider",
        "once_cell",
        "zerovec",
        ]
        
        [[package]]
        name = "boa_interner"
        version = "0.16.0"
        source = "git+https://github.com/boa-dev/boa?rev=08a72387ba5cd185f657e98d984ff2ce328da69e#08a72387ba5cd185f657e98d984ff2ce328da69e"
        dependencies = [
        "boa_macros",
        "hashbrown 0.13.2",
        "indexmap",
        "once_cell",
        "phf",
        "rustc-hash",
        "static_assertions",
        ]
        
        [[package]]
        name = "boa_macros"
        version = "0.16.0"
        source = "git+https://github.com/boa-dev/boa?rev=08a72387ba5cd185f657e98d984ff2ce328da69e#08a72387ba5cd185f657e98d984ff2ce328da69e"
        dependencies = [
        "proc-macro2",
        "quote",
        "syn 2.0.15",
        "synstructure 0.13.0",
        ]
        
        [[package]]
        name = "boa_parser"
        version = "0.16.0"
        source = "git+https://github.com/boa-dev/boa?rev=08a72387ba5cd185f657e98d984ff2ce328da69e#08a72387ba5cd185f657e98d984ff2ce328da69e"
        dependencies = [
        "bitflags 2.2.1",
        "boa_ast",
        "boa_icu_provider",
        "boa_interner",
        "boa_macros",
        "boa_profiler",
        "fast-float",
        "icu_properties",
        "num-bigint",
        "num-traits",
        "once_cell",
        "regress",
        "rustc-hash",
        ]
        
        [[package]]
        name = "boa_profiler"
        version = "0.16.0"
        source = "git+https://github.com/boa-dev/boa?rev=08a72387ba5cd185f657e98d984ff2ce328da69e#08a72387ba5cd185f657e98d984ff2ce328da69e"
        
        [[package]]
        name = "bumpalo"
        version = "3.12.1"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "9b1ce199063694f33ffb7dd4e0ee620741495c32833cde5aa08f02a0bf96f0c8"
        
        [[package]]
        name = "byteorder"
        version = "1.4.3"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "14c189c53d098945499cdfa7ecc63567cf3886b3332b312a5b4585d8d3a6a610"
        
        [[package]]
        name = "candid"
        version = "0.8.4"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "244005a1917bb7614cd775ca8a5d59efeb5ac74397bb14ba29a19347ebd78591"
        dependencies = [
        "anyhow",
        "binread",
        "byteorder",
        "candid_derive 0.5.0",
        "codespan-reporting",
        "crc32fast",
        "data-encoding",
        "hex",
        "lalrpop",
        "lalrpop-util",
        "leb128",
        "logos",
        "num-bigint",
        "num-traits",
        "num_enum 0.5.11",
        "paste",
        "pretty",
        "serde",
        "serde_bytes",
        "sha2",
        "thiserror",
        ]
        
        [[package]]
        name = "candid"
        version = "0.9.0-beta.3"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "2ee0d6ee2234fc18021430aad8c6125f6856407014f2c2e8baf74c236427dbfc"
        dependencies = [
        "anyhow",
        "binread",
        "byteorder",
        "candid_derive 0.6.0",
        "codespan-reporting",
        "crc32fast",
        "data-encoding",
        "hex",
        "lalrpop",
        "lalrpop-util",
        "leb128",
        "logos",
        "num-bigint",
        "num-traits",
        "num_enum 0.5.11",
        "paste",
        "pretty",
        "serde",
        "serde_bytes",
        "sha2",
        "stacker",
        "thiserror",
        ]
        
        [[package]]
        name = "candid_derive"
        version = "0.5.0"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "58f1f4db7c7d04b87b70b3a35c5dc5c2c9dd73cef8bdf6760e2f18a0d45350dd"
        dependencies = [
        "lazy_static",
        "proc-macro2",
        "quote",
        "syn 1.0.109",
        ]
        
        [[package]]
        name = "candid_derive"
        version = "0.6.0"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "34df46ac8b0a44de9b243d9dd21e608838183be20de408c934993ed6a4a8e4c1"
        dependencies = [
        "lazy_static",
        "proc-macro2",
        "quote",
        "syn 1.0.109",
        ]
        
        [[package]]
        name = "cc"
        version = "1.0.79"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "50d30906286121d95be3d479533b458f87493b30a4b5f79a607db8f5d11aa91f"
        
        [[package]]
        name = "cdk_framework"
        version = "0.0.0"
        source = "git+https://github.com/demergent-labs/cdk_framework?rev=13c4abdd72bdcfa6a5b1ddf7f08a4fd83eacb419#13c4abdd72bdcfa6a5b1ddf7f08a4fd83eacb419"
        dependencies = [
        "proc-macro2",
        "quote",
        "regex",
        ]
        
        [[package]]
        name = "cfg-if"
        version = "1.0.0"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "baf1de4339761588bc0619e3cbc0120ee582ebb74b53b4efbf79117bd2da40fd"
        
        [[package]]
        name = "chrono"
        version = "0.4.24"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "4e3c5919066adf22df73762e50cffcde3a758f2a848b113b586d1f86728b673b"
        dependencies = [
        "iana-time-zone",
        "num-integer",
        "num-traits",
        "winapi",
        ]
        
        [[package]]
        name = "codespan-reporting"
        version = "0.11.1"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "3538270d33cc669650c4b093848450d380def10c331d38c768e34cac80576e6e"
        dependencies = [
        "termcolor",
        "unicode-width",
        ]
        
        [[package]]
        name = "core-foundation-sys"
        version = "0.8.4"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "e496a50fda8aacccc86d7529e2c1e0892dbd0f898a6b5645b5561b89c3210efa"
        
        [[package]]
        name = "cpufeatures"
        version = "0.2.7"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "3e4c1eaa2012c47becbbad2ab175484c2a84d1185b566fb2cc5b8707343dfe58"
        dependencies = [
        "libc",
        ]
        
        [[package]]
        name = "crc32fast"
        version = "1.3.2"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "b540bd8bc810d3885c6ea91e2018302f68baba2129ab3e88f32389ee9370880d"
        dependencies = [
        "cfg-if",
        ]
        
        [[package]]
        name = "critical-section"
        version = "1.1.1"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "6548a0ad5d2549e111e1f6a11a6c2e2d00ce6a3dafe22948d67c2b443f775e52"
        
        [[package]]
        name = "crunchy"
        version = "0.2.2"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "7a81dae078cea95a014a339291cec439d2f232ebe854a9d672b796c6afafa9b7"
        
        [[package]]
        name = "crypto-common"
        version = "0.1.6"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "1bfb12502f3fc46cca1bb51ac28df9d618d813cdc3d2f25b9fe775a34af26bb3"
        dependencies = [
        "generic-array",
        "typenum",
        ]
        
        [[package]]
        name = "cxx"
        version = "1.0.94"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "f61f1b6389c3fe1c316bf8a4dccc90a38208354b330925bce1f74a6c4756eb93"
        dependencies = [
        "cc",
        "cxxbridge-flags",
        "cxxbridge-macro",
        "link-cplusplus",
        ]
        
        [[package]]
        name = "cxx-build"
        version = "1.0.94"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "12cee708e8962df2aeb38f594aae5d827c022b6460ac71a7a3e2c3c2aae5a07b"
        dependencies = [
        "cc",
        "codespan-reporting",
        "once_cell",
        "proc-macro2",
        "quote",
        "scratch",
        "syn 2.0.15",
        ]
        
        [[package]]
        name = "cxxbridge-flags"
        version = "1.0.94"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "7944172ae7e4068c533afbb984114a56c46e9ccddda550499caa222902c7f7bb"
        
        [[package]]
        name = "cxxbridge-macro"
        version = "1.0.94"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "2345488264226bf682893e25de0769f3360aac9957980ec49361b083ddaa5bc5"
        dependencies = [
        "proc-macro2",
        "quote",
        "syn 2.0.15",
        ]
        
        [[package]]
        name = "darling"
        version = "0.13.4"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "a01d95850c592940db9b8194bc39f4bc0e89dee5c4265e4b1807c34a9aba453c"
        dependencies = [
        "darling_core",
        "darling_macro",
        ]
        
        [[package]]
        name = "darling_core"
        version = "0.13.4"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "859d65a907b6852c9361e3185c862aae7fafd2887876799fa55f5f99dc40d610"
        dependencies = [
        "fnv",
        "ident_case",
        "proc-macro2",
        "quote",
        "strsim",
        "syn 1.0.109",
        ]
        
        [[package]]
        name = "darling_macro"
        version = "0.13.4"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "9c972679f83bdf9c42bd905396b6c3588a843a17f0f16dfcfa3e2c5d57441835"
        dependencies = [
        "darling_core",
        "quote",
        "syn 1.0.109",
        ]
        
        [[package]]
        name = "dashmap"
        version = "5.4.0"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "907076dfda823b0b36d2a1bb5f90c96660a5bbcd7729e10727f07858f22c4edc"
        dependencies = [
        "cfg-if",
        "hashbrown 0.12.3",
        "lock_api",
        "once_cell",
        "parking_lot_core",
        ]
        
        [[package]]
        name = "data-encoding"
        version = "2.3.3"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "23d8666cb01533c39dde32bcbab8e227b4ed6679b2c925eba05feabea39508fb"
        
        [[package]]
        name = "debug_unreachable"
        version = "0.1.1"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "9a032eac705ca39214d169f83e3d3da290af06d8d1d344d1baad2fd002dca4b3"
        dependencies = [
        "unreachable",
        ]
        
        [[package]]
        name = "diff"
        version = "0.1.13"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "56254986775e3233ffa9c4d7d3faaf6d36a2c09d30b20687e9f88bc8bafc16c8"
        
        [[package]]
        name = "digest"
        version = "0.10.6"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "8168378f4e5023e7218c89c891c0fd8ecdb5e5e4f18cb78f38cf245dd021e76f"
        dependencies = [
        "block-buffer",
        "crypto-common",
        ]
        
        [[package]]
        name = "dirs-next"
        version = "2.0.0"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "b98cf8ebf19c3d1b223e151f99a4f9f0690dca41414773390fc824184ac833e1"
        dependencies = [
        "cfg-if",
        "dirs-sys-next",
        ]
        
        [[package]]
        name = "dirs-sys-next"
        version = "0.1.2"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "4ebda144c4fe02d1f7ea1a7d9641b6fc6b580adcfa024ae48797ecdeb6825b4d"
        dependencies = [
        "libc",
        "redox_users",
        "winapi",
        ]
        
        [[package]]
        name = "displaydoc"
        version = "0.2.4"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "487585f4d0c6655fe74905e2504d8ad6908e4db67f744eb140876906c2f3175d"
        dependencies = [
        "proc-macro2",
        "quote",
        "syn 2.0.15",
        ]
        
        [[package]]
        name = "either"
        version = "1.8.1"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "7fcaabb2fef8c910e7f4c7ce9f67a1283a1715879a7c230ca9d6d1ae31f16d91"
        
        [[package]]
        name = "ena"
        version = "0.14.2"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "c533630cf40e9caa44bd91aadc88a75d75a4c3a12b4cfde353cbed41daa1e1f1"
        dependencies = [
        "log",
        ]
        
        [[package]]
        name = "enum_kind"
        version = "0.2.2"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "9895954c6ec59d897ed28a64815f2ceb57653fcaaebd317f2edc78b74f5495b6"
        dependencies = [
        "pmutil",
        "proc-macro2",
        "swc_macros_common",
        "syn 1.0.109",
        ]
        
        [[package]]
        name = "errno"
        version = "0.3.1"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "4bcfec3a70f97c962c307b2d2c56e358cf1d00b558d74262b5f929ee8cc7e73a"
        dependencies = [
        "errno-dragonfly",
        "libc",
        "windows-sys 0.48.0",
        ]
        
        [[package]]
        name = "errno-dragonfly"
        version = "0.1.2"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "aa68f1b12764fab894d2755d2518754e71b4fd80ecfb822714a1206c2aab39bf"
        dependencies = [
        "cc",
        "libc",
        ]
        
        [[package]]
        name = "fast-float"
        version = "0.2.0"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "95765f67b4b18863968b4a1bd5bb576f732b29a4a28c7cd84c09fa3e2875f33c"
        
        [[package]]
        name = "fixedbitset"
        version = "0.4.2"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "0ce7134b9999ecaf8bcd65542e436736ef32ddca1b3e06094cb6ec5755203b80"
        
        [[package]]
        name = "fnv"
        version = "1.0.7"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "3f9eec918d3f24069decb9af1554cad7c880e2da24a9afd88aca000531ab82c1"
        
        [[package]]
        name = "form_urlencoded"
        version = "1.1.0"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "a9c384f161156f5260c24a097c56119f9be8c798586aecc13afbcbe7b7e26bf8"
        dependencies = [
        "percent-encoding",
        ]
        
        [[package]]
        name = "from_variant"
        version = "0.1.5"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "1d449976075322384507443937df2f1d5577afbf4282f12a5a66ef29fa3e6307"
        dependencies = [
        "pmutil",
        "proc-macro2",
        "swc_macros_common",
        "syn 1.0.109",
        ]
        
        [[package]]
        name = "futures"
        version = "0.3.28"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "23342abe12aba583913b2e62f22225ff9c950774065e4bfb61a19cd9770fec40"
        dependencies = [
        "futures-channel",
        "futures-core",
        "futures-executor",
        "futures-io",
        "futures-sink",
        "futures-task",
        "futures-util",
        ]
        
        [[package]]
        name = "futures-channel"
        version = "0.3.28"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "955518d47e09b25bbebc7a18df10b81f0c766eaf4c4f1cccef2fca5f2a4fb5f2"
        dependencies = [
        "futures-core",
        "futures-sink",
        ]
        
        [[package]]
        name = "futures-core"
        version = "0.3.28"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "4bca583b7e26f571124fe5b7561d49cb2868d79116cfa0eefce955557c6fee8c"
        
        [[package]]
        name = "futures-executor"
        version = "0.3.28"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "ccecee823288125bd88b4d7f565c9e58e41858e47ab72e8ea2d64e93624386e0"
        dependencies = [
        "futures-core",
        "futures-task",
        "futures-util",
        ]
        
        [[package]]
        name = "futures-io"
        version = "0.3.28"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "4fff74096e71ed47f8e023204cfd0aa1289cd54ae5430a9523be060cdb849964"
        
        [[package]]
        name = "futures-macro"
        version = "0.3.28"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "89ca545a94061b6365f2c7355b4b32bd20df3ff95f02da9329b34ccc3bd6ee72"
        dependencies = [
        "proc-macro2",
        "quote",
        "syn 2.0.15",
        ]
        
        [[package]]
        name = "futures-sink"
        version = "0.3.28"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "f43be4fe21a13b9781a69afa4985b0f6ee0e1afab2c6f454a8cf30e2b2237b6e"
        
        [[package]]
        name = "futures-task"
        version = "0.3.28"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "76d3d132be6c0e6aa1534069c705a74a5997a356c0dc2f86a47765e5617c5b65"
        
        [[package]]
        name = "futures-util"
        version = "0.3.28"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "26b01e40b772d54cf6c6d721c1d1abd0647a0106a12ecaa1c186273392a69533"
        dependencies = [
        "futures-channel",
        "futures-core",
        "futures-io",
        "futures-macro",
        "futures-sink",
        "futures-task",
        "memchr",
        "pin-project-lite",
        "pin-utils",
        "slab",
        ]
        
        [[package]]
        name = "generic-array"
        version = "0.14.7"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "85649ca51fd72272d7821adaf274ad91c288277713d9c18820d8499a7ff69e9a"
        dependencies = [
        "typenum",
        "version_check",
        ]
        
        [[package]]
        name = "getrandom"
        version = "0.2.3"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "7fcd999463524c52659517fe2cea98493cfe485d10565e7b0fb07dbba7ad2753"
        dependencies = [
        "cfg-if",
        "libc",
        "wasi",
        ]
        
        [[package]]
        name = "hashbrown"
        version = "0.12.3"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "8a9ee70c43aaf417c914396645a0fa852624801b24ebb7ae78fe8272889ac888"
        
        [[package]]
        name = "hashbrown"
        version = "0.13.2"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "43a3c133739dddd0d2990f9a4bdf8eb4b21ef50e4851ca85ab661199821d510e"
        dependencies = [
        "ahash 0.8.3",
        ]
        
        [[package]]
        name = "hermit-abi"
        version = "0.3.1"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "fed44880c466736ef9a5c5b5facefb5ed0785676d0c02d612db14e54f0d84286"
        
        [[package]]
        name = "hex"
        version = "0.4.3"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "7f24254aa9a54b5c858eaee2f5bccdb46aaf0e486a595ed5fd8f86ba55232a70"
        
        [[package]]
        name = "iana-time-zone"
        version = "0.1.56"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "0722cd7114b7de04316e7ea5456a0bbb20e4adb46fd27a3697adb812cff0f37c"
        dependencies = [
        "android_system_properties",
        "core-foundation-sys",
        "iana-time-zone-haiku",
        "js-sys",
        "wasm-bindgen",
        "windows",
        ]
        
        [[package]]
        name = "iana-time-zone-haiku"
        version = "0.1.1"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "0703ae284fc167426161c2e3f1da3ea71d94b21bedbcc9494e92b28e334e3dca"
        dependencies = [
        "cxx",
        "cxx-build",
        ]
        
        [[package]]
        name = "ic-cdk"
        version = "0.7.4"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "9beb0bf1dcd0639c313630e34aa547a2b19450ddf1969c176e13225ef3b29048"
        dependencies = [
        "candid 0.8.4",
        "ic-cdk-macros 0.6.10",
        "ic0",
        "serde",
        "serde_bytes",
        ]
        
        [[package]]
        name = "ic-cdk"
        version = "0.8.0-beta.0"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "229a2796b731794363b45ab7b3a8ae28dc4220256997709e52746887425c5135"
        dependencies = [
        "candid 0.9.0-beta.3",
        "ic-cdk-macros 0.8.0-beta.0",
        "ic0",
        "serde",
        "serde_bytes",
        ]
        
        [[package]]
        name = "ic-cdk-macros"
        version = "0.6.10"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "ebf50458685a0fc6b0e414cdba487610aeb199ac94db52d9fd76270565debee7"
        dependencies = [
        "candid 0.8.4",
        "proc-macro2",
        "quote",
        "serde",
        "serde_tokenstream",
        "syn 1.0.109",
        ]
        
        [[package]]
        name = "ic-cdk-macros"
        version = "0.8.0-beta.0"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "a8ed566a9a45e97f8dd7eed3db58c95875272dbf053f0d94a965319cbffdb9e0"
        dependencies = [
        "candid 0.9.0-beta.3",
        "proc-macro2",
        "quote",
        "serde",
        "serde_tokenstream",
        "syn 1.0.109",
        ]
        
        [[package]]
        name = "ic-cdk-timers"
        version = "0.1.2"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "c739e7c592cb66df4f15c6b6c4859b1195782f63923e2fb1b29553d9c0819bd4"
        dependencies = [
        "futures",
        "ic-cdk 0.7.4",
        "ic0",
        "serde",
        "serde_bytes",
        "slotmap",
        ]
        
        [[package]]
        name = "ic-stable-structures"
        version = "0.5.2"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "7d43ba7c5067d1360860e2234d93411d2126c8eac788467966ed1383161f91fc"
        
        [[package]]
        name = "ic0"
        version = "0.18.9"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "978b91fc78de9d2eb0144db717839cde3b35470199ea51aca362cb6310e93dfd"
        
        [[package]]
        name = "icu_collections"
        version = "1.2.0"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "ef8302d8dfd6044d3ddb3f807a5ef3d7bbca9a574959c6d6e4dc39aa7012d0d5"
        dependencies = [
        "displaydoc",
        "yoke",
        "zerofrom",
        "zerovec",
        ]
        
        [[package]]
        name = "icu_locid"
        version = "1.2.0"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "3003f85dccfc0e238ff567693248c59153a46f4e6125ba4020b973cef4d1d335"
        dependencies = [
        "displaydoc",
        "litemap",
        "tinystr",
        "writeable",
        ]
        
        [[package]]
        name = "icu_normalizer"
        version = "1.2.0"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "652869735c9fb9f5a64ba180ee16f2c848390469c116deef517ecc53f4343598"
        dependencies = [
        "displaydoc",
        "icu_collections",
        "icu_properties",
        "icu_provider",
        "smallvec",
        "utf16_iter",
        "utf8_iter",
        "write16",
        "zerovec",
        ]
        
        [[package]]
        name = "icu_properties"
        version = "1.2.0"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "ce0e1aa26851f16c9e04412a5911c86b7f8768dac8f8d4c5f1c568a7e5d7a434"
        dependencies = [
        "displaydoc",
        "icu_collections",
        "icu_provider",
        "tinystr",
        "zerovec",
        ]
        
        [[package]]
        name = "icu_provider"
        version = "1.2.0"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "8dc312a7b6148f7dfe098047ae2494d12d4034f48ade58d4f353000db376e305"
        dependencies = [
        "displaydoc",
        "icu_locid",
        "icu_provider_macros",
        "serde",
        "stable_deref_trait",
        "writeable",
        "yoke",
        "zerofrom",
        "zerovec",
        ]
        
        [[package]]
        name = "icu_provider_macros"
        version = "1.2.0"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "dd8b728b9421e93eff1d9f8681101b78fa745e0748c95c655c83f337044a7e10"
        dependencies = [
        "proc-macro2",
        "quote",
        "syn 1.0.109",
        ]
        
        [[package]]
        name = "ident_case"
        version = "1.0.1"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "b9e0384b61958566e926dc50660321d12159025e767c18e043daf26b70104c39"
        
        [[package]]
        name = "idna"
        version = "0.3.0"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "e14ddfc70884202db2244c223200c204c2bda1bc6e0998d11b5e024d657209e6"
        dependencies = [
        "unicode-bidi",
        "unicode-normalization",
        ]
        
        [[package]]
        name = "indexmap"
        version = "1.9.3"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "bd070e393353796e801d209ad339e89596eb4c8d430d18ede6a1cced8fafbd99"
        dependencies = [
        "autocfg",
        "hashbrown 0.12.3",
        ]
        
        [[package]]
        name = "io-lifetimes"
        version = "1.0.10"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "9c66c74d2ae7e79a5a8f7ac924adbe38ee42a859c6539ad869eb51f0b52dc220"
        dependencies = [
        "hermit-abi",
        "libc",
        "windows-sys 0.48.0",
        ]
        
        [[package]]
        name = "is-macro"
        version = "0.2.2"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "8a7d079e129b77477a49c5c4f1cfe9ce6c2c909ef52520693e8e811a714c7b20"
        dependencies = [
        "Inflector",
        "pmutil",
        "proc-macro2",
        "quote",
        "syn 1.0.109",
        ]
        
        [[package]]
        name = "is-terminal"
        version = "0.4.7"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "adcf93614601c8129ddf72e2d5633df827ba6551541c6d8c59520a371475be1f"
        dependencies = [
        "hermit-abi",
        "io-lifetimes",
        "rustix",
        "windows-sys 0.48.0",
        ]
        
        [[package]]
        name = "itertools"
        version = "0.10.5"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "b0fd2260e829bddf4cb6ea802289de2f86d6a7a690192fbe91b3f46e0f2c8473"
        dependencies = [
        "either",
        ]
        
        [[package]]
        name = "itoa"
        version = "1.0.6"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "453ad9f582a441959e5f0d088b02ce04cfe8d51a8eaf077f12ac6d3e94164ca6"
        
        [[package]]
        name = "js-sys"
        version = "0.3.61"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "445dde2150c55e483f3d8416706b97ec8e8237c307e5b7b4b8dd15e6af2a0730"
        dependencies = [
        "wasm-bindgen",
        ]
        
        [[package]]
        name = "lalrpop"
        version = "0.19.12"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "0a1cbf952127589f2851ab2046af368fd20645491bb4b376f04b7f94d7a9837b"
        dependencies = [
        "ascii-canvas",
        "bit-set",
        "diff",
        "ena",
        "is-terminal",
        "itertools",
        "lalrpop-util",
        "petgraph",
        "regex",
        "regex-syntax 0.6.29",
        "string_cache",
        "term",
        "tiny-keccak",
        "unicode-xid",
        ]
        
        [[package]]
        name = "lalrpop-util"
        version = "0.19.12"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "d3c48237b9604c5a4702de6b824e02006c3214327564636aef27c1028a8fa0ed"
        dependencies = [
        "regex",
        ]
        
        [[package]]
        name = "lazy_static"
        version = "1.4.0"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "e2abad23fbc42b3700f2f279844dc832adb2b2eb069b2df918f455c4e18cc646"
        
        [[package]]
        name = "leb128"
        version = "0.2.5"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "884e2677b40cc8c339eaefcb701c32ef1fd2493d71118dc0ca4b6a736c93bd67"
        
        [[package]]
        name = "lexical"
        version = "6.1.1"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "c7aefb36fd43fef7003334742cbf77b243fcd36418a1d1bdd480d613a67968f6"
        dependencies = [
        "lexical-core",
        ]
        
        [[package]]
        name = "lexical-core"
        version = "0.8.5"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "2cde5de06e8d4c2faabc400238f9ae1c74d5412d03a7bd067645ccbc47070e46"
        dependencies = [
        "lexical-parse-float",
        "lexical-parse-integer",
        "lexical-util",
        "lexical-write-float",
        "lexical-write-integer",
        ]
        
        [[package]]
        name = "lexical-parse-float"
        version = "0.8.5"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "683b3a5ebd0130b8fb52ba0bdc718cc56815b6a097e28ae5a6997d0ad17dc05f"
        dependencies = [
        "lexical-parse-integer",
        "lexical-util",
        "static_assertions",
        ]
        
        [[package]]
        name = "lexical-parse-integer"
        version = "0.8.6"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "6d0994485ed0c312f6d965766754ea177d07f9c00c9b82a5ee62ed5b47945ee9"
        dependencies = [
        "lexical-util",
        "static_assertions",
        ]
        
        [[package]]
        name = "lexical-util"
        version = "0.8.5"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "5255b9ff16ff898710eb9eb63cb39248ea8a5bb036bea8085b1a767ff6c4e3fc"
        dependencies = [
        "static_assertions",
        ]
        
        [[package]]
        name = "lexical-write-float"
        version = "0.8.5"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "accabaa1c4581f05a3923d1b4cfd124c329352288b7b9da09e766b0668116862"
        dependencies = [
        "lexical-util",
        "lexical-write-integer",
        "static_assertions",
        ]
        
        [[package]]
        name = "lexical-write-integer"
        version = "0.8.5"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "e1b6f3d1f4422866b68192d62f77bc5c700bee84f3069f2469d7bc8c77852446"
        dependencies = [
        "lexical-util",
        "static_assertions",
        ]
        
        [[package]]
        name = "libc"
        version = "0.2.142"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "6a987beff54b60ffa6d51982e1aa1146bc42f19bd26be28b0586f252fccf5317"
        
        [[package]]
        name = "link-cplusplus"
        version = "1.0.8"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "ecd207c9c713c34f95a097a5b029ac2ce6010530c7b49d7fea24d977dede04f5"
        dependencies = [
        "cc",
        ]
        
        [[package]]
        name = "linux-raw-sys"
        version = "0.3.7"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "ece97ea872ece730aed82664c424eb4c8291e1ff2480247ccf7409044bc6479f"
        
        [[package]]
        name = "litemap"
        version = "0.7.0"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "3a04a5b2b6f54acba899926491d0a6c59d98012938ca2ab5befb281c034e8f94"
        
        [[package]]
        name = "lock_api"
        version = "0.4.9"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "435011366fe56583b16cf956f9df0095b405b82d76425bc8981c0e22e60ec4df"
        dependencies = [
        "autocfg",
        "scopeguard",
        ]
        
        [[package]]
        name = "log"
        version = "0.4.17"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "abb12e687cfb44aa40f41fc3978ef76448f9b6038cad6aef4259d3c095a2382e"
        dependencies = [
        "cfg-if",
        ]
        
        [[package]]
        name = "logos"
        version = "0.12.1"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "bf8b031682c67a8e3d5446840f9573eb7fe26efe7ec8d195c9ac4c0647c502f1"
        dependencies = [
        "logos-derive",
        ]
        
        [[package]]
        name = "logos-derive"
        version = "0.12.1"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "a1d849148dbaf9661a6151d1ca82b13bb4c4c128146a88d05253b38d4e2f496c"
        dependencies = [
        "beef",
        "fnv",
        "proc-macro2",
        "quote",
        "regex-syntax 0.6.29",
        "syn 1.0.109",
        ]
        
        [[package]]
        name = "memchr"
        version = "2.5.0"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "2dffe52ecf27772e601905b7522cb4ef790d2cc203488bbd0e2fe85fcb74566d"
        
        [[package]]
        name = "new_debug_unreachable"
        version = "1.0.4"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "e4a24736216ec316047a1fc4252e27dabb04218aa4a3f37c6e7ddbf1f9782b54"
        
        [[package]]
        name = "num-bigint"
        version = "0.4.3"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "f93ab6289c7b344a8a9f60f88d80aa20032336fe78da341afc91c8a2341fc75f"
        dependencies = [
        "autocfg",
        "num-integer",
        "num-traits",
        "serde",
        ]
        
        [[package]]
        name = "num-integer"
        version = "0.1.45"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "225d3389fb3509a24c93f5c29eb6bde2586b98d9f016636dff58d7c6f7569cd9"
        dependencies = [
        "autocfg",
        "num-traits",
        ]
        
        [[package]]
        name = "num-traits"
        version = "0.2.15"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "578ede34cf02f8924ab9447f50c28075b4d3e5b269972345e7e0372b38c6cdcd"
        dependencies = [
        "autocfg",
        ]
        
        [[package]]
        name = "num_enum"
        version = "0.5.11"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "1f646caf906c20226733ed5b1374287eb97e3c2a5c227ce668c1f2ce20ae57c9"
        dependencies = [
        "num_enum_derive 0.5.11",
        ]
        
        [[package]]
        name = "num_enum"
        version = "0.6.1"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "7a015b430d3c108a207fd776d2e2196aaf8b1cf8cf93253e3a097ff3085076a1"
        dependencies = [
        "num_enum_derive 0.6.1",
        ]
        
        [[package]]
        name = "num_enum_derive"
        version = "0.5.11"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "dcbff9bc912032c62bf65ef1d5aea88983b420f4f839db1e9b0c281a25c9c799"
        dependencies = [
        "proc-macro-crate",
        "proc-macro2",
        "quote",
        "syn 1.0.109",
        ]
        
        [[package]]
        name = "num_enum_derive"
        version = "0.6.1"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "96667db765a921f7b295ffee8b60472b686a51d4f21c2ee4ffdb94c7013b65a6"
        dependencies = [
        "proc-macro-crate",
        "proc-macro2",
        "quote",
        "syn 2.0.15",
        ]
        
        [[package]]
        name = "once_cell"
        version = "1.17.1"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "b7e5500299e16ebb147ae15a00a942af264cf3688f47923b8fc2cd5858f23ad3"
        dependencies = [
        "atomic-polyfill",
        "critical-section",
        ]
        
        [[package]]
        name = "parking_lot"
        version = "0.12.1"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "3742b2c103b9f06bc9fff0a37ff4912935851bee6d36f3c02bcc755bcfec228f"
        dependencies = [
        "lock_api",
        "parking_lot_core",
        ]
        
        [[package]]
        name = "parking_lot_core"
        version = "0.9.7"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "9069cbb9f99e3a5083476ccb29ceb1de18b9118cafa53e90c9551235de2b9521"
        dependencies = [
        "cfg-if",
        "libc",
        "redox_syscall",
        "smallvec",
        "windows-sys 0.45.0",
        ]
        
        [[package]]
        name = "paste"
        version = "1.0.12"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "9f746c4065a8fa3fe23974dd82f15431cc8d40779821001404d10d2e79ca7d79"
        
        [[package]]
        name = "percent-encoding"
        version = "2.2.0"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "478c572c3d73181ff3c2539045f6eb99e5491218eae919370993b890cdbdd98e"
        
        [[package]]
        name = "petgraph"
        version = "0.6.3"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "4dd7d28ee937e54fe3080c91faa1c3a46c06de6252988a7f4592ba2310ef22a4"
        dependencies = [
        "fixedbitset",
        "indexmap",
        ]
        
        [[package]]
        name = "phf"
        version = "0.11.1"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "928c6535de93548188ef63bb7c4036bd415cd8f36ad25af44b9789b2ee72a48c"
        dependencies = [
        "phf_macros",
        "phf_shared 0.11.1",
        ]
        
        [[package]]
        name = "phf_generator"
        version = "0.10.0"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "5d5285893bb5eb82e6aaf5d59ee909a06a16737a8970984dd7746ba9283498d6"
        dependencies = [
        "phf_shared 0.10.0",
        "rand",
        ]
        
        [[package]]
        name = "phf_generator"
        version = "0.11.1"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "b1181c94580fa345f50f19d738aaa39c0ed30a600d95cb2d3e23f94266f14fbf"
        dependencies = [
        "phf_shared 0.11.1",
        "rand",
        ]
        
        [[package]]
        name = "phf_macros"
        version = "0.11.1"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "92aacdc5f16768709a569e913f7451034034178b05bdc8acda226659a3dccc66"
        dependencies = [
        "phf_generator 0.11.1",
        "phf_shared 0.11.1",
        "proc-macro2",
        "quote",
        "syn 1.0.109",
        ]
        
        [[package]]
        name = "phf_shared"
        version = "0.10.0"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "b6796ad771acdc0123d2a88dc428b5e38ef24456743ddb1744ed628f9815c096"
        dependencies = [
        "siphasher",
        ]
        
        [[package]]
        name = "phf_shared"
        version = "0.11.1"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "e1fb5f6f826b772a8d4c0394209441e7d37cbbb967ae9c7e0e8134365c9ee676"
        dependencies = [
        "siphasher",
        ]
        
        [[package]]
        name = "pin-project-lite"
        version = "0.2.9"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "e0a7ae3ac2f1173085d398531c705756c94a4c56843785df85a60c1a0afac116"
        
        [[package]]
        name = "pin-utils"
        version = "0.1.0"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "8b870d8c151b6f2fb93e84a13146138f05d02ed11c7e7c54f8826aaaf7c9f184"
        
        [[package]]
        name = "pmutil"
        version = "0.5.3"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "3894e5d549cccbe44afecf72922f277f603cd4bb0219c8342631ef18fffbe004"
        dependencies = [
        "proc-macro2",
        "quote",
        "syn 1.0.109",
        ]
        
        [[package]]
        name = "pollster"
        version = "0.3.0"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "22686f4785f02a4fcc856d3b3bb19bf6c8160d103f7a99cc258bddd0251dc7f2"
        
        [[package]]
        name = "ppv-lite86"
        version = "0.2.17"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "5b40af805b3121feab8a3c29f04d8ad262fa8e0561883e7653e024ae4479e6de"
        
        [[package]]
        name = "precomputed-hash"
        version = "0.1.1"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "925383efa346730478fb4838dbe9137d2a47675ad789c546d150a6e1dd4ab31c"
        
        [[package]]
        name = "pretty"
        version = "0.10.0"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "ad9940b913ee56ddd94aec2d3cd179dd47068236f42a1a6415ccf9d880ce2a61"
        dependencies = [
        "arrayvec",
        "typed-arena",
        ]
        
        [[package]]
        name = "prettyplease"
        version = "0.2.4"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "1ceca8aaf45b5c46ec7ed39fff75f57290368c1846d33d24a122ca81416ab058"
        dependencies = [
        "proc-macro2",
        "syn 2.0.15",
        ]
        
        [[package]]
        name = "proc-macro-crate"
        version = "1.3.1"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "7f4c021e1093a56626774e81216a4ce732a735e5bad4868a03f3ed65ca0c3919"
        dependencies = [
        "once_cell",
        "toml_edit",
        ]
        
        [[package]]
        name = "proc-macro2"
        version = "1.0.56"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "2b63bdb0cd06f1f4dedf69b254734f9b45af66e4a031e42a7480257d9898b435"
        dependencies = [
        "unicode-ident",
        ]
        
        [[package]]
        name = "psm"
        version = "0.1.21"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "5787f7cda34e3033a72192c018bc5883100330f362ef279a8cbccfce8bb4e874"
        dependencies = [
        "cc",
        ]
        
        [[package]]
        name = "quote"
        version = "1.0.26"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "4424af4bf778aae2051a77b60283332f386554255d722233d09fbfc7e30da2fc"
        dependencies = [
        "proc-macro2",
        ]
        
        [[package]]
        name = "rand"
        version = "0.8.5"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "34af8d1a0e25924bc5b7c43c079c942339d8f0a8b57c39049bef581b46327404"
        dependencies = [
        "libc",
        "rand_chacha",
        "rand_core",
        ]
        
        [[package]]
        name = "rand_chacha"
        version = "0.3.1"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "e6c10a63a0fa32252be49d21e7709d4d4baf8d231c2dbce1eaa8141b9b127d88"
        dependencies = [
        "ppv-lite86",
        "rand_core",
        ]
        
        [[package]]
        name = "rand_core"
        version = "0.6.4"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "ec0be4795e2f6a28069bec0b5ff3e2ac9bafc99e6a9a7dc3547996c5c816922c"
        dependencies = [
        "getrandom",
        ]
        
        [[package]]
        name = "redox_syscall"
        version = "0.2.16"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "fb5a58c1855b4b6819d59012155603f0b22ad30cad752600aadfcb695265519a"
        dependencies = [
        "bitflags 1.3.2",
        ]
        
        [[package]]
        name = "redox_users"
        version = "0.4.3"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "b033d837a7cf162d7993aded9304e30a83213c648b6e389db233191f891e5c2b"
        dependencies = [
        "getrandom",
        "redox_syscall",
        "thiserror",
        ]
        
        [[package]]
        name = "regex"
        version = "1.8.1"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "af83e617f331cc6ae2da5443c602dfa5af81e517212d9d611a5b3ba1777b5370"
        dependencies = [
        "aho-corasick",
        "memchr",
        "regex-syntax 0.7.1",
        ]
        
        [[package]]
        name = "regex-syntax"
        version = "0.6.29"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "f162c6dd7b008981e4d40210aca20b4bd0f9b60ca9271061b07f78537722f2e1"
        
        [[package]]
        name = "regex-syntax"
        version = "0.7.1"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "a5996294f19bd3aae0453a862ad728f60e6600695733dd5df01da90c54363a3c"
        
        [[package]]
        name = "regress"
        version = "0.6.0"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "82a9ecfa0cb04d0b04dddb99b8ccf4f66bc8dfd23df694b398570bd8ae3a50fb"
        dependencies = [
        "hashbrown 0.13.2",
        "memchr",
        ]
        
        [[package]]
        name = "rustc-hash"
        version = "1.1.0"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "08d43f7aa6b08d49f382cde6a7982047c3426db949b1424bc4b7ec9ae12c6ce2"
        
        [[package]]
        name = "rustix"
        version = "0.37.19"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "acf8729d8542766f1b2cf77eb034d52f40d375bb8b615d0b147089946e16613d"
        dependencies = [
        "bitflags 1.3.2",
        "errno",
        "io-lifetimes",
        "libc",
        "linux-raw-sys",
        "windows-sys 0.48.0",
        ]
        
        [[package]]
        name = "rustversion"
        version = "1.0.12"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "4f3208ce4d8448b3f3e7d168a73f5e0c43a61e32930de3bceeccedb388b6bf06"
        
        [[package]]
        name = "ryu"
        version = "1.0.13"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "f91339c0467de62360649f8d3e185ca8de4224ff281f66000de5eb2a77a79041"
        
        [[package]]
        name = "ryu-js"
        version = "0.2.2"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "6518fc26bced4d53678a22d6e423e9d8716377def84545fe328236e3af070e7f"
        
        [[package]]
        name = "scoped-tls"
        version = "1.0.1"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "e1cf6437eb19a8f4a6cc0f7dca544973b0b78843adbfeb3683d1a94a0024a294"
        
        [[package]]
        name = "scopeguard"
        version = "1.1.0"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "d29ab0c6d3fc0ee92fe66e2d99f700eab17a8d57d1c1d3b748380fb20baa78cd"
        
        [[package]]
        name = "scratch"
        version = "1.0.5"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "1792db035ce95be60c3f8853017b3999209281c24e2ba5bc8e59bf97a0c590c1"
        
        [[package]]
        name = "serde"
        version = "1.0.160"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "bb2f3770c8bce3bcda7e149193a069a0f4365bda1fa5cd88e03bca26afc1216c"
        dependencies = [
        "serde_derive",
        ]
        
        [[package]]
        name = "serde_bytes"
        version = "0.11.9"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "416bda436f9aab92e02c8e10d49a15ddd339cea90b6e340fe51ed97abb548294"
        dependencies = [
        "serde",
        ]
        
        [[package]]
        name = "serde_derive"
        version = "1.0.160"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "291a097c63d8497e00160b166a967a4a79c64f3facdd01cbd7502231688d77df"
        dependencies = [
        "proc-macro2",
        "quote",
        "syn 2.0.15",
        ]
        
        [[package]]
        name = "serde_json"
        version = "1.0.96"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "057d394a50403bcac12672b2b18fb387ab6d289d957dab67dd201875391e52f1"
        dependencies = [
        "itoa",
        "ryu",
        "serde",
        ]
        
        [[package]]
        name = "serde_tokenstream"
        version = "0.1.7"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "797ba1d80299b264f3aac68ab5d12e5825a561749db4df7cd7c8083900c5d4e9"
        dependencies = [
        "proc-macro2",
        "serde",
        "syn 1.0.109",
        ]
        
        [[package]]
        name = "sha2"
        version = "0.10.6"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "82e6b795fe2e3b1e845bafcb27aa35405c4d47cdfc92af5fc8d3002f76cebdc0"
        dependencies = [
        "cfg-if",
        "cpufeatures",
        "digest",
        ]
        
        [[package]]
        name = "siphasher"
        version = "0.3.10"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "7bd3e3206899af3f8b12af284fafc038cc1dc2b41d1b89dd17297221c5d225de"
        
        [[package]]
        name = "slab"
        version = "0.4.8"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "6528351c9bc8ab22353f9d776db39a20288e8d6c37ef8cfe3317cf875eecfc2d"
        dependencies = [
        "autocfg",
        ]
        
        [[package]]
        name = "slotmap"
        version = "1.0.6"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "e1e08e261d0e8f5c43123b7adf3e4ca1690d655377ac93a03b2c9d3e98de1342"
        dependencies = [
        "version_check",
        ]
        
        [[package]]
        name = "smallvec"
        version = "1.10.0"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "a507befe795404456341dfab10cef66ead4c041f62b8b11bbb92bffe5d0953e0"
        
        [[package]]
        name = "sptr"
        version = "0.3.2"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "3b9b39299b249ad65f3b7e96443bad61c02ca5cd3589f46cb6d610a0fd6c0d6a"
        
        [[package]]
        name = "stable_deref_trait"
        version = "1.2.0"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "a8f112729512f8e442d81f95a8a7ddf2b7c6b8a1a6f509a95864142b30cab2d3"
        
        [[package]]
        name = "stacker"
        version = "0.1.15"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "c886bd4480155fd3ef527d45e9ac8dd7118a898a46530b7b94c3e21866259fce"
        dependencies = [
        "cc",
        "cfg-if",
        "libc",
        "psm",
        "winapi",
        ]
        
        [[package]]
        name = "static_assertions"
        version = "1.1.0"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "a2eb9349b6444b326872e140eb1cf5e7c522154d69e7a0ffb0fb81c06b37543f"
        
        [[package]]
        name = "string_cache"
        version = "0.8.7"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "f91138e76242f575eb1d3b38b4f1362f10d3a43f47d182a5b359af488a02293b"
        dependencies = [
        "new_debug_unreachable",
        "once_cell",
        "parking_lot",
        "phf_shared 0.10.0",
        "precomputed-hash",
        "serde",
        ]
        
        [[package]]
        name = "string_cache_codegen"
        version = "0.5.2"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "6bb30289b722be4ff74a408c3cc27edeaad656e06cb1fe8fa9231fa59c728988"
        dependencies = [
        "phf_generator 0.10.0",
        "phf_shared 0.10.0",
        "proc-macro2",
        "quote",
        ]
        
        [[package]]
        name = "string_enum"
        version = "0.3.4"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "91f42363e5ca94ea6f3faee9e3b5e1a4047535ae323f5c0579385fb2ae95874e"
        dependencies = [
        "pmutil",
        "proc-macro2",
        "quote",
        "swc_macros_common",
        "syn 1.0.109",
        ]
        
        [[package]]
        name = "strsim"
        version = "0.10.0"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "73473c0e59e6d5812c5dfe2a064a6444949f089e20eec9a2e5506596494e4623"
        
        [[package]]
        name = "swc_atoms"
        version = "0.4.43"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "64593af3e0fbacd1b7147a0188f1fd77a2fc8ae3c2425bdb9528de255b9f452b"
        dependencies = [
        "once_cell",
        "rustc-hash",
        "serde",
        "string_cache",
        "string_cache_codegen",
        "triomphe",
        ]
        
        [[package]]
        name = "swc_common"
        version = "0.27.16"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "49b0b6107e44797d0549bdb5b47a97682c3b914140269c01d2acdb16a1b885f6"
        dependencies = [
        "ahash 0.7.6",
        "ast_node",
        "better_scoped_tls",
        "cfg-if",
        "debug_unreachable",
        "either",
        "from_variant",
        "num-bigint",
        "once_cell",
        "rustc-hash",
        "serde",
        "siphasher",
        "string_cache",
        "swc_atoms",
        "swc_eq_ignore_macros",
        "swc_visit",
        "tracing",
        "unicode-width",
        "url",
        ]
        
        [[package]]
        name = "swc_ecma_ast"
        version = "0.90.20"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "f712949db06518bec7b7e050aa3bcde749a74fbf79f4f520ab179d0445b63593"
        dependencies = [
        "bitflags 1.3.2",
        "is-macro",
        "num-bigint",
        "scoped-tls",
        "serde",
        "string_enum",
        "swc_atoms",
        "swc_common",
        "unicode-id",
        ]
        
        [[package]]
        name = "swc_ecma_parser"
        version = "0.117.7"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "d88ffca99514bc8bfa8bf4f2d74fb673caa844e521b55035b8cfd10472b801d4"
        dependencies = [
        "either",
        "enum_kind",
        "lexical",
        "num-bigint",
        "serde",
        "smallvec",
        "swc_atoms",
        "swc_common",
        "swc_ecma_ast",
        "tracing",
        "typed-arena",
        ]
        
        [[package]]
        name = "swc_eq_ignore_macros"
        version = "0.1.1"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "0c20468634668c2bbab581947bb8c75c97158d5a6959f4ba33df20983b20b4f6"
        dependencies = [
        "pmutil",
        "proc-macro2",
        "quote",
        "syn 1.0.109",
        ]
        
        [[package]]
        name = "swc_macros_common"
        version = "0.3.7"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "3e582c3e3c2269238524923781df5be49e011dbe29cf7683a2215d600a562ea6"
        dependencies = [
        "pmutil",
        "proc-macro2",
        "quote",
        "syn 1.0.109",
        ]
        
        [[package]]
        name = "swc_visit"
        version = "0.5.5"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "d1d5999f23421c8e21a0f2bc53a0b9e8244f3b421de89471561af2fbe40b9cca"
        dependencies = [
        "either",
        "swc_visit_macros",
        ]
        
        [[package]]
        name = "swc_visit_macros"
        version = "0.5.6"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "ebeed7eb0f545f48ad30f5aab314e5208b735bcea1d1464f26e20f06db904989"
        dependencies = [
        "Inflector",
        "pmutil",
        "proc-macro2",
        "quote",
        "swc_macros_common",
        "syn 1.0.109",
        ]
        
        [[package]]
        name = "syn"
        version = "1.0.109"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "72b64191b275b66ffe2469e8af2c1cfe3bafa67b529ead792a6d0160888b4237"
        dependencies = [
        "proc-macro2",
        "quote",
        "unicode-ident",
        ]
        
        [[package]]
        name = "syn"
        version = "2.0.15"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "a34fcf3e8b60f57e6a14301a2e916d323af98b0ea63c599441eec8558660c822"
        dependencies = [
        "proc-macro2",
        "quote",
        "unicode-ident",
        ]
        
        [[package]]
        name = "synstructure"
        version = "0.12.6"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "f36bdaa60a83aca3921b5259d5400cbf5e90fc51931376a9bd4a0eb79aa7210f"
        dependencies = [
        "proc-macro2",
        "quote",
        "syn 1.0.109",
        "unicode-xid",
        ]
        
        [[package]]
        name = "synstructure"
        version = "0.13.0"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "285ba80e733fac80aa4270fbcdf83772a79b80aa35c97075320abfee4a915b06"
        dependencies = [
        "proc-macro2",
        "quote",
        "syn 2.0.15",
        "unicode-xid",
        ]
        
        [[package]]
        name = "tap"
        version = "1.0.1"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "55937e1799185b12863d447f42597ed69d9928686b8d88a1df17376a097d8369"
        
        [[package]]
        name = "term"
        version = "0.7.0"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "c59df8ac95d96ff9bede18eb7300b0fda5e5d8d90960e76f8e14ae765eedbf1f"
        dependencies = [
        "dirs-next",
        "rustversion",
        "winapi",
        ]
        
        [[package]]
        name = "termcolor"
        version = "1.2.0"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "be55cf8942feac5c765c2c993422806843c9a9a45d4d5c407ad6dd2ea95eb9b6"
        dependencies = [
        "winapi-util",
        ]
        
        [[package]]
        name = "thin-vec"
        version = "0.2.12"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "aac81b6fd6beb5884b0cf3321b8117e6e5d47ecb6fc89f414cfdcca8b2fe2dd8"
        
        [[package]]
        name = "thiserror"
        version = "1.0.40"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "978c9a314bd8dc99be594bc3c175faaa9794be04a5a5e153caba6915336cebac"
        dependencies = [
        "thiserror-impl",
        ]
        
        [[package]]
        name = "thiserror-impl"
        version = "1.0.40"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "f9456a42c5b0d803c8cd86e73dd7cc9edd429499f37a3550d286d5e86720569f"
        dependencies = [
        "proc-macro2",
        "quote",
        "syn 2.0.15",
        ]
        
        [[package]]
        name = "tiny-keccak"
        version = "2.0.2"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "2c9d3793400a45f954c52e73d068316d76b6f4e36977e3fcebb13a2721e80237"
        dependencies = [
        "crunchy",
        ]
        
        [[package]]
        name = "tinystr"
        version = "0.7.1"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "7ac3f5b6856e931e15e07b478e98c8045239829a65f9156d4fa7e7788197a5ef"
        dependencies = [
        "displaydoc",
        "zerovec",
        ]
        
        [[package]]
        name = "tinyvec"
        version = "1.6.0"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "87cc5ceb3875bb20c2890005a4e226a4651264a5c75edb2421b52861a0a0cb50"
        dependencies = [
        "tinyvec_macros",
        ]
        
        [[package]]
        name = "tinyvec_macros"
        version = "0.1.1"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "1f3ccbac311fea05f86f61904b462b55fb3df8837a366dfc601a0161d0532f20"
        
        [[package]]
        name = "toml_datetime"
        version = "0.6.1"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "3ab8ed2edee10b50132aed5f331333428b011c99402b5a534154ed15746f9622"
        
        [[package]]
        name = "toml_edit"
        version = "0.19.8"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "239410c8609e8125456927e6707163a3b1fdb40561e4b803bc041f466ccfdc13"
        dependencies = [
        "indexmap",
        "toml_datetime",
        "winnow",
        ]
        
        [[package]]
        name = "tracing"
        version = "0.1.37"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "8ce8c33a8d48bd45d624a6e523445fd21ec13d3653cd51f681abf67418f54eb8"
        dependencies = [
        "cfg-if",
        "pin-project-lite",
        "tracing-attributes",
        "tracing-core",
        ]
        
        [[package]]
        name = "tracing-attributes"
        version = "0.1.24"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "0f57e3ca2a01450b1a921183a9c9cbfda207fd822cef4ccb00a65402cbba7a74"
        dependencies = [
        "proc-macro2",
        "quote",
        "syn 2.0.15",
        ]
        
        [[package]]
        name = "tracing-core"
        version = "0.1.30"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "24eb03ba0eab1fd845050058ce5e616558e8f8d8fca633e6b163fe25c797213a"
        dependencies = [
        "once_cell",
        ]
        
        [[package]]
        name = "triomphe"
        version = "0.1.8"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "f1ee9bd9239c339d714d657fac840c6d2a4f9c45f4f9ec7b0975113458be78db"
        dependencies = [
        "serde",
        "stable_deref_trait",
        ]
        
        [[package]]
        name = "typed-arena"
        version = "2.0.2"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "6af6ae20167a9ece4bcb41af5b80f8a1f1df981f6391189ce00fd257af04126a"
        
        [[package]]
        name = "typenum"
        version = "1.16.0"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "497961ef93d974e23eb6f433eb5fe1b7930b659f06d12dec6fc44a8f554c0bba"
        
        [[package]]
        name = "unicode-bidi"
        version = "0.3.13"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "92888ba5573ff080736b3648696b70cafad7d250551175acbaa4e0385b3e1460"
        
        [[package]]
        name = "unicode-id"
        version = "0.3.3"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "d70b6494226b36008c8366c288d77190b3fad2eb4c10533139c1c1f461127f1a"
        
        [[package]]
        name = "unicode-ident"
        version = "1.0.8"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "e5464a87b239f13a63a501f2701565754bae92d243d4bb7eb12f6d57d2269bf4"
        
        [[package]]
        name = "unicode-normalization"
        version = "0.1.22"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "5c5713f0fc4b5db668a2ac63cdb7bb4469d8c9fed047b1d0292cc7b0ce2ba921"
        dependencies = [
        "tinyvec",
        ]
        
        [[package]]
        name = "unicode-width"
        version = "0.1.10"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "c0edd1e5b14653f783770bce4a4dabb4a5108a5370a5f5d8cfe8710c361f6c8b"
        
        [[package]]
        name = "unicode-xid"
        version = "0.2.4"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "f962df74c8c05a667b5ee8bcf162993134c104e96440b663c8daa176dc772d8c"
        
        [[package]]
        name = "unreachable"
        version = "0.1.1"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "1f2ae5ddb18e1c92664717616dd9549dde73f539f01bd7b77c2edb2446bdff91"
        dependencies = [
        "void",
        ]
        
        [[package]]
        name = "url"
        version = "2.3.1"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "0d68c799ae75762b8c3fe375feb6600ef5602c883c5d21eb51c09f22b83c4643"
        dependencies = [
        "form_urlencoded",
        "idna",
        "percent-encoding",
        ]
        
        [[package]]
        name = "utf16_iter"
        version = "1.0.4"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "52df8b7fb78e7910d776fccf2e42ceaf3604d55e8e7eb2dbd183cb1441d8a692"
        
        [[package]]
        name = "utf8_iter"
        version = "1.0.3"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "64a8922555b9500e3d865caed19330172cd67cbf82203f1a3311d8c305cc9f33"
        
        [[package]]
        name = "uuid"
        version = "1.2.2"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "422ee0de9031b5b948b97a8fc04e3aa35230001a722ddd27943e0be31564ce4c"
        dependencies = [
        "getrandom",
        ]
        
        [[package]]
        name = "version_check"
        version = "0.9.4"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "49874b5167b65d7193b8aba1567f5c7d93d001cafc34600cee003eda787e483f"
        
        [[package]]
        name = "void"
        version = "1.0.2"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "6a02e4885ed3bc0f2de90ea6dd45ebcbb66dacffe03547fadbb0eeae2770887d"
        
        [[package]]
        name = "wasi"
        version = "0.10.2+wasi-snapshot-preview1"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "fd6fbd9a79829dd1ad0cc20627bf1ed606756a7f77edff7b66b7064f9cb327c6"
        
        [[package]]
        name = "wasm-bindgen"
        version = "0.2.84"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "31f8dcbc21f30d9b8f2ea926ecb58f6b91192c17e9d33594b3df58b2007ca53b"
        dependencies = [
        "cfg-if",
        "wasm-bindgen-macro",
        ]
        
        [[package]]
        name = "wasm-bindgen-backend"
        version = "0.2.84"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "95ce90fd5bcc06af55a641a86428ee4229e44e07033963a2290a8e241607ccb9"
        dependencies = [
        "bumpalo",
        "log",
        "once_cell",
        "proc-macro2",
        "quote",
        "syn 1.0.109",
        "wasm-bindgen-shared",
        ]
        
        [[package]]
        name = "wasm-bindgen-macro"
        version = "0.2.84"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "4c21f77c0bedc37fd5dc21f897894a5ca01e7bb159884559461862ae90c0b4c5"
        dependencies = [
        "quote",
        "wasm-bindgen-macro-support",
        ]
        
        [[package]]
        name = "wasm-bindgen-macro-support"
        version = "0.2.84"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "2aff81306fcac3c7515ad4e177f521b5c9a15f2b08f4e32d823066102f35a5f6"
        dependencies = [
        "proc-macro2",
        "quote",
        "syn 1.0.109",
        "wasm-bindgen-backend",
        "wasm-bindgen-shared",
        ]
        
        [[package]]
        name = "wasm-bindgen-shared"
        version = "0.2.84"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "0046fef7e28c3804e5e38bfa31ea2a0f73905319b677e57ebe37e49358989b5d"
        
        [[package]]
        name = "winapi"
        version = "0.3.9"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "5c839a674fcd7a98952e593242ea400abe93992746761e38641405d28b00f419"
        dependencies = [
        "winapi-i686-pc-windows-gnu",
        "winapi-x86_64-pc-windows-gnu",
        ]
        
        [[package]]
        name = "winapi-i686-pc-windows-gnu"
        version = "0.4.0"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "ac3b87c63620426dd9b991e5ce0329eff545bccbbb34f3be09ff6fb6ab51b7b6"
        
        [[package]]
        name = "winapi-util"
        version = "0.1.5"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "70ec6ce85bb158151cae5e5c87f95a8e97d2c0c4b001223f33a334e3ce5de178"
        dependencies = [
        "winapi",
        ]
        
        [[package]]
        name = "winapi-x86_64-pc-windows-gnu"
        version = "0.4.0"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "712e227841d057c1ee1cd2fb22fa7e5a5461ae8e48fa2ca79ec42cfc1931183f"
        
        [[package]]
        name = "windows"
        version = "0.48.0"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "e686886bc078bc1b0b600cac0147aadb815089b6e4da64016cbd754b6342700f"
        dependencies = [
        "windows-targets 0.48.0",
        ]
        
        [[package]]
        name = "windows-sys"
        version = "0.45.0"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "75283be5efb2831d37ea142365f009c02ec203cd29a3ebecbc093d52315b66d0"
        dependencies = [
        "windows-targets 0.42.2",
        ]
        
        [[package]]
        name = "windows-sys"
        version = "0.48.0"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "677d2418bec65e3338edb076e806bc1ec15693c5d0104683f2efe857f61056a9"
        dependencies = [
        "windows-targets 0.48.0",
        ]
        
        [[package]]
        name = "windows-targets"
        version = "0.42.2"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "8e5180c00cd44c9b1c88adb3693291f1cd93605ded80c250a75d472756b4d071"
        dependencies = [
        "windows_aarch64_gnullvm 0.42.2",
        "windows_aarch64_msvc 0.42.2",
        "windows_i686_gnu 0.42.2",
        "windows_i686_msvc 0.42.2",
        "windows_x86_64_gnu 0.42.2",
        "windows_x86_64_gnullvm 0.42.2",
        "windows_x86_64_msvc 0.42.2",
        ]
        
        [[package]]
        name = "windows-targets"
        version = "0.48.0"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "7b1eb6f0cd7c80c79759c929114ef071b87354ce476d9d94271031c0497adfd5"
        dependencies = [
        "windows_aarch64_gnullvm 0.48.0",
        "windows_aarch64_msvc 0.48.0",
        "windows_i686_gnu 0.48.0",
        "windows_i686_msvc 0.48.0",
        "windows_x86_64_gnu 0.48.0",
        "windows_x86_64_gnullvm 0.48.0",
        "windows_x86_64_msvc 0.48.0",
        ]
        
        [[package]]
        name = "windows_aarch64_gnullvm"
        version = "0.42.2"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "597a5118570b68bc08d8d59125332c54f1ba9d9adeedeef5b99b02ba2b0698f8"
        
        [[package]]
        name = "windows_aarch64_gnullvm"
        version = "0.48.0"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "91ae572e1b79dba883e0d315474df7305d12f569b400fcf90581b06062f7e1bc"
        
        [[package]]
        name = "windows_aarch64_msvc"
        version = "0.42.2"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "e08e8864a60f06ef0d0ff4ba04124db8b0fb3be5776a5cd47641e942e58c4d43"
        
        [[package]]
        name = "windows_aarch64_msvc"
        version = "0.48.0"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "b2ef27e0d7bdfcfc7b868b317c1d32c641a6fe4629c171b8928c7b08d98d7cf3"
        
        [[package]]
        name = "windows_i686_gnu"
        version = "0.42.2"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "c61d927d8da41da96a81f029489353e68739737d3beca43145c8afec9a31a84f"
        
        [[package]]
        name = "windows_i686_gnu"
        version = "0.48.0"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "622a1962a7db830d6fd0a69683c80a18fda201879f0f447f065a3b7467daa241"
        
        [[package]]
        name = "windows_i686_msvc"
        version = "0.42.2"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "44d840b6ec649f480a41c8d80f9c65108b92d89345dd94027bfe06ac444d1060"
        
        [[package]]
        name = "windows_i686_msvc"
        version = "0.48.0"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "4542c6e364ce21bf45d69fdd2a8e455fa38d316158cfd43b3ac1c5b1b19f8e00"
        
        [[package]]
        name = "windows_x86_64_gnu"
        version = "0.42.2"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "8de912b8b8feb55c064867cf047dda097f92d51efad5b491dfb98f6bbb70cb36"
        
        [[package]]
        name = "windows_x86_64_gnu"
        version = "0.48.0"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "ca2b8a661f7628cbd23440e50b05d705db3686f894fc9580820623656af974b1"
        
        [[package]]
        name = "windows_x86_64_gnullvm"
        version = "0.42.2"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "26d41b46a36d453748aedef1486d5c7a85db22e56aff34643984ea85514e94a3"
        
        [[package]]
        name = "windows_x86_64_gnullvm"
        version = "0.48.0"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "7896dbc1f41e08872e9d5e8f8baa8fdd2677f29468c4e156210174edc7f7b953"
        
        [[package]]
        name = "windows_x86_64_msvc"
        version = "0.42.2"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "9aec5da331524158c6d1a4ac0ab1541149c0b9505fde06423b02f5ef0106b9f0"
        
        [[package]]
        name = "windows_x86_64_msvc"
        version = "0.48.0"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "1a515f5799fe4961cb532f983ce2b23082366b898e52ffbce459c86f67c8378a"
        
        [[package]]
        name = "winnow"
        version = "0.4.6"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "61de7bac303dc551fe038e2b3cef0f571087a47571ea6e79a87692ac99b99699"
        dependencies = [
        "memchr",
        ]
        
        [[package]]
        name = "write16"
        version = "1.0.0"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "d1890f4022759daae28ed4fe62859b1236caebfc61ede2f63ed4e695f3f6d936"
        
        [[package]]
        name = "writeable"
        version = "0.5.2"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "60e49e42bdb1d5dc76f4cd78102f8f0714d32edfa3efb82286eb0f0b1fc0da0f"
        
        [[package]]
        name = "yoke"
        version = "0.7.1"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "1848075a23a28f9773498ee9a0f2cf58fcbad4f8c0ccf84a210ab33c6ae495de"
        dependencies = [
        "serde",
        "stable_deref_trait",
        "yoke-derive",
        "zerofrom",
        ]
        
        [[package]]
        name = "yoke-derive"
        version = "0.7.1"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "af46c169923ed7516eef0aa32b56d2651b229f57458ebe46b49ddd6efef5b7a2"
        dependencies = [
        "proc-macro2",
        "quote",
        "syn 1.0.109",
        "synstructure 0.12.6",
        ]
        
        [[package]]
        name = "zerofrom"
        version = "0.1.2"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "df54d76c3251de27615dfcce21e636c172dafb2549cd7fd93e21c66f6ca6bea2"
        dependencies = [
        "zerofrom-derive",
        ]
        
        [[package]]
        name = "zerofrom-derive"
        version = "0.1.2"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "b4eae7c1f7d4b8eafce526bc0771449ddc2f250881ae31c50d22c032b5a1c499"
        dependencies = [
        "proc-macro2",
        "quote",
        "syn 1.0.109",
        "synstructure 0.12.6",
        ]
        
        [[package]]
        name = "zerovec"
        version = "0.9.4"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "198f54134cd865f437820aa3b43d0ad518af4e68ee161b444cdd15d8e567c8ea"
        dependencies = [
        "yoke",
        "zerofrom",
        "zerovec-derive",
        ]
        
        [[package]]
        name = "zerovec-derive"
        version = "0.9.4"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "486558732d5dde10d0f8cb2936507c1bb21bc539d924c949baf5f36a58e51bac"
        dependencies = [
        "proc-macro2",
        "quote",
        "syn 1.0.109",
        "synstructure 0.12.6",
        ]
    `;
}
