pub use ast_traits::FunctionAndMethodTypeHelperMethods;
pub use ast_traits::GenerateInlineName;
pub use ast_traits::GetDependencies;
pub use ast_traits::GetName;
pub use ast_traits::GetSourceText;
pub use ast_traits::GetTsType;
pub use azle_fn_decl::AzleFnDecl;
pub use azle_type::AzleArrayType;
pub use azle_type::AzleFnOrConstructorType;
pub use azle_type::AzleKeywordType;
pub use azle_type::AzleTupleType;
pub use azle_type::AzleTypeLit;
pub use azle_type::AzleTypeRef;
pub use ts_ast::TsAst;
pub use type_alias_decls::AzleTypeAliasDecl;

pub mod ast_traits;
mod ts_ast;
mod ts_fn_type;
mod ts_keyword_type;
mod ts_method_signature;
mod ts_tuple_type;
mod ts_type;
mod ts_type_ann;
mod ts_type_element;
mod ts_type_lit;
mod ts_type_ref;

pub mod azle_fn_decl;
pub mod azle_type;
pub mod ident;
pub mod module;
pub mod program;
pub mod source_map;
pub mod ts_fn_param;
pub mod type_alias_decls;
