use cdk_framework::act::node::{
    data_type::type_annotation::ToTypeAnnotation, ExternalCanisterMethod,
};
use proc_macro2::{Ident, TokenStream};
use quote::{format_ident, quote};

use crate::ts_keywords;

pub mod functions;
pub mod register_function;

pub fn generate_param_variables(
    method: &ExternalCanisterMethod,
    canister_name: String,
) -> Vec<TokenStream> {
    method.params
        .iter()
        .enumerate()
        .map(|(index, param)| {
            let param_name_js_value = format_ident!("{}_js_value", &param.prefixed_name());
            let param_name = format_ident!("{}", &param.prefixed_name());
            let parental_prefix = format!("{}{}", canister_name, method.name);
            let param_type = param.type_.to_type_annotation(&ts_keywords::ts_keywords(), format!("{}_{}", parental_prefix, index));
            // TODO: param_type should likely be generated by the CDK Framework with create_param_type_annotation

            quote! {
                let #param_name_js_value = args_js_object.get(#index, _context).unwrap();
                let #param_name: #param_type = #param_name_js_value.try_from_vm_value(&mut *_context).unwrap();
            }
        })
    .collect()
}

pub fn generate_args_list(method: &ExternalCanisterMethod) -> TokenStream {
    let param_names: Vec<Ident> = method
        .params
        .iter()
        .map(|param| format_ident!("{}", &param.prefixed_name()))
        .collect();

    let comma = if param_names.len() == 1 {
        quote! { , }
    } else {
        quote! {}
    };
    return quote! { (#(#param_names),*#comma) };
}
