pub mod functions;

pub fn generate_ic_object() -> proc_macro2::TokenStream {
    quote::quote! {
        let ic = boa_engine::object::ObjectInitializer::new(&mut _azle_boa_context)
            .function(
                _azle_ic_accept_message,
                "accept_message",
                0
            )
            .function(
                _azle_ic_arg_data_raw,
                "arg_data_raw",
                0
            )
            .function(
                _azle_ic_arg_data_raw_size,
                "arg_data_raw_size",
                0
            )
            .function(
                _azle_ic_caller,
                "caller",
                0
            )
            .function(
                _azle_ic_candid_decode,
                "candid_decode",
                0
            )
            .function(
                _azle_ic_candid_encode,
                "candid_encode",
                0
            )
            .function(
                _azle_ic_canister_balance,
                "canister_balance",
                0
            )
            .function(
                _azle_ic_canister_balance128,
                "canister_balance128",
                0
            )
            .function(
                _azle_ic_data_certificate,
                "data_certificate",
                0
            )
            .function(
                _azle_ic_id,
                "id",
                0
            )
            .function(
                _azle_ic_method_name,
                "method_name",
                0
            )
            .function(
                _azle_ic_notify_raw,
                "notify_raw",
                0
            )
            .function(
                _azle_ic_performance_counter,
                "performance_counter",
                0
            )
            .function(
                _azle_ic_print,
                "print",
                0
            )
            .function(
                _azle_ic_reject,
                "reject",
                0
            )
            .function(
                _azle_ic_reply,
                "reply",
                0
            )
            .function(
                _azle_ic_set_certified_data,
                "set_certified_data",
                0
            )
            .function(
                _azle_ic_stable_bytes,
                "stable_bytes",
                0
            )
            .function(
                _azle_ic_stable_grow,
                "stable_grow",
                0
            )
            .function(
                _azle_ic_stable_read,
                "stable_read",
                0
            )
            .function(
                _azle_ic_stable_size,
                "stable_size",
                0
            )
            .function(
                _azle_ic_stable_write,
                "stable_write",
                0
            )
            .function(
                _azle_ic_stable64_grow,
                "stable64_grow",
                0
            )
            .function(
                _azle_ic_stable64_read,
                "stable64_read",
                0
            )
            .function(
                _azle_ic_stable64_size,
                "stable64_size",
                0
            )
            .function(
                _azle_ic_stable64_write,
                "stable64_write",
                0
            )
            .function(
                _azle_ic_time,
                "time",
                0
            )
            .function(
                _azle_ic_trap,
                "trap",
                0
            )
            .property(
                "_azle_stable_storage",
                _azle_stable_storage,
                boa_engine::property::Attribute::all()
            )
            .build();
    }
}
