name: Commit and Push Changes
description: 'Commits and pushes changes using GraphQL for App-signed commits'

inputs:
    branch-name:
        description: 'Name of the branch to push to'
        required: true
    create-branch:
        description: 'Whether to create the branch if it does not exist'
        required: false
        default: 'false'
    commit-message:
        description: 'Commit message'
        required: true
    add-files:
        description: 'File pattern to git add. Defaults to "--all"'
        required: false
        default: '--all'
    token:
        description: 'GitHub App token with repo access'
        required: true
    github-token:
        description: 'GITHUB_TOKEN for git operations (branch creation)'
        required: false
        default: ''

runs:
    using: composite
    steps:
        - name: Create branch if requested
          if: inputs.create-branch == 'true'
          shell: bash
          env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: |
              git fetch origin
              git checkout -b ${{ steps.create-branch-name.outputs.branch-name }} ${{ needs.create-branch-prefix.outputs.base-branch }}
              git push --set-upstream origin ${{ steps.create-branch-name.outputs.branch-name }}

        - name: Commit via GraphQL Script
          shell: bash
          env:
              GITHUB_TOKEN: ${{ inputs.token }}
              BRANCH_NAME: ${{ inputs.branch-name }}
              CREATE_BRANCH: ${{ inputs.create-branch }}
              COMMIT_MESSAGE: ${{ inputs.commit-message }}
              ADD_FILES: ${{ inputs.add-files }}
          run: ./.github/actions/commit_and_push/run.sh
