name: Commit and Push Changes
description: 'Configures git, commits changes, and pushes to a new branch'
inputs:
    branch-name:
        description: 'Name of the branch to push to'
        required: true
    create-branch:
        description: 'Whether to create a new branch'
        required: false
        default: 'false'
    commit-message:
        description: 'Commit message'
        required: true
    gpg_signing_key:
        description: 'The GPG signing key to use for signing commits'
        required: true
runs:
    using: composite
    steps:
        - uses: ./.github/actions/configure_git
          with:
              gpg_signing_key: ${{ inputs.gpg_signing_key }}

        - name: Commit and push changes
          shell: bash
          run: |
              # Create new branch if requested
              if [ "${{ inputs.create-branch }}" = "true" ]; then
                  git switch -c "${{ inputs.branch-name }}"
              else
                  git switch "${{ inputs.branch-name }}"
              fi

              # Show status of working directory
              echo "Current git status:"
              git status

              # Add and commit changes if there are any
              git add --all
              if ! git diff --cached --quiet; then
                git commit -m "${{ inputs.commit-message }}"
                git push origin "${{ inputs.branch-name }}"
              else
                # The above commands exit with 1 if there are no changes to commit
                echo "No changes to commit. Skipping commit and push."
              fi
