name: Commit and Push Changes
description: 'Configures git, commits changes, and pushes to an existing branch'
inputs:
    branch-name:
        description: 'Name of the branch to push to'
        required: true
    commit-message:
        description: 'Commit message'
        required: true
    add-files:
        description: 'Optional file pattern to limit git add. E.g. "src/" to only add changes from the src directory. Defaults to "--all" to add all changes.'
        required: false
        default: '--all'
    token:
        description: 'GitHub App token with repo access'
        required: true

runs:
    using: composite
    steps:
        - name: Commit via GraphQL Script
          shell: bash
          env:
              GITHUB_TOKEN: ${{ inputs.token }}
              BRANCH_NAME: ${{ inputs.branch-name }}
              COMMIT_MESSAGE: ${{ inputs.commit-message }}
              ADD_FILES: ${{ inputs.add-files }}
          run: ./.github/actions/commit_and_push/commit_and_push.sh
