name: 'Setup Node.js'
description: 'Sets up Node.js environment and gets Node version from package.json'
inputs:
    node-auth-token:
        description: 'NPM authentication token'
        required: false
    registry-url:
        description: 'NPM registry URL'
        required: false
    working-directory:
        description: 'Directory containing package.json (defaults to current directory)'
        required: false
        default: '.'
outputs:
    node-version:
        description: 'The Node.js version from package.json'
        value: ${{ steps.get-version.outputs.version }}

runs:
    using: 'composite'
    steps:
        - id: get-version
          shell: bash
          run: |
              PACKAGE_JSON_PATH="${{ inputs.working-directory }}/package.json"
              VERSION=$(jq -r '.azle.globalDependencies.node // error("node version not found")' "$PACKAGE_JSON_PATH")
              echo "version=$VERSION" >> $GITHUB_OUTPUT

        - uses: actions/setup-node@v4
          with:
              registry-url: ${{ inputs.registry-url }}
              node-version: ${{ steps.get-version.outputs.version }}
          env:
              NODE_AUTH_TOKEN: ${{ inputs.node-auth-token }}
