[package]
name = "azle_generate"
version = "0.0.0"
edition = "2018"

[lib]
proc_macro = true

[dependencies]
quote = "1.0.21"
syn = "1.0.99"
proc-macro2 = "1.0.43"
swc_common = "0.27.10"
swc_ecma_parser = "0.117.4"
derive-syn-parse = "0.1.5"
swc_ecma_ast = "0.90.10"
