name: 'Command with retries'
description: 'Run any command with exponential backoff retries'

inputs:
    command:
        description: 'Command to execute'
        required: true
    working-directory:
        description: 'Directory where to run the command'
        required: false
        default: '.'
    max-attempts:
        description: 'Maximum number of retry attempts'
        required: false
        default: '5'
    initial-delay:
        description: 'Initial delay in seconds before first retry'
        required: false
        default: '1'
    max-delay:
        description: 'Maximum delay in seconds between retries'
        required: false
        default: '60'

runs:
    using: 'composite'
    steps:
        - shell: bash
          run: |
              attempt=1
              max_attempts=${{ inputs.max-attempts }}
              delay=${{ inputs.initial-delay }}
              max_delay=${{ inputs.max-delay }}

              echo "Maximum attempts: $max_attempts"
              echo "Maximum delay: $max_delay"
              total_max_delay=$(($max_attempts * $max_delay))
              echo "Total maximum possible delay: $total_max_delay seconds"

              until cd ${{ inputs.working-directory }} && ${{ inputs.command }}; do
                if [ $attempt -ge $max_attempts ]; then
                  echo "Command failed after $attempt attempts"
                  exit 1
                fi

                attempt=$(($attempt + 1))
                echo "Command failed, retrying in $delay seconds... (attempt $attempt/$max_attempts)"
                sleep $delay

                # Exponential backoff with a configurable maximum
                delay=$(( delay * 2 ))
                if [ $delay -gt $max_delay ]; then
                  delay=$max_delay
                fi
              done
