use crate::body::stable_b_tree_map::StableBTreeMapNode;

mod macros;
mod ref_cells;
mod use_statements;

pub fn generate(
    main_js: &str,
    stable_b_tree_map_nodes: &Vec<StableBTreeMapNode>,
) -> proc_macro2::TokenStream {
    let use_statements = use_statements::generate();
    let macros = macros::generate();
    let ref_cells = ref_cells::generate(stable_b_tree_map_nodes);

    quote::quote! {
        // This code is automatically generated by Azle

        #![allow(warnings, unused)]

        #use_statements
        #macros
        #ref_cells

        pub mod javascript {
            pub static MAIN_JS: &'static str = #main_js;
        }
    }
}
