name: Get Exclude Directories
description: 'Gets a list of directories to exclude based on input parameters'
inputs:
    exclude-slow:
        description: 'Whether to exclude slow benchmarks'
        required: true
    exclude-unstable:
        description: 'Whether to exclude unstable benchmarks'
        required: true
    exclude-release-only:
        description: 'Whether to exclude release only benchmarks'
        required: true
outputs:
    exclude-dirs:
        description: 'Space-separated list of directories to exclude'
        value: ${{ steps.set-exclude-dirs.outputs.exclude-dirs }}
runs:
    using: composite
    steps:
        - id: set-exclude-dirs
          shell: bash
          run: |
              RELEASE_ONLY_EXCLUSIONS="${{ format('
              examples/stable/test/end_to_end/candid_rpc/new
              examples/experimental/test/end_to_end/http_server/new
              ') }}"

              UNSTABLE_EXCLUSIONS="${{ format('
              examples/stable/test/end_to_end/candid_rpc/multi_deploy
              examples/stable/test/property/candid_rpc/stable_b_tree_map
              examples/stable/test/property/ic_api/performance_counter
              examples/stable/test/property/ic_api/instruction_counter
              examples/experimental/demo/basic_bitcoin
              examples/experimental/demo/bitcoin_psbt
              examples/experimental/demo/ckbtc
              examples/experimental/test/end_to_end/http_server/ethers_base
              examples/experimental/test/end_to_end/http_server/http_outcall_fetch
              examples/experimental/test/end_to_end/http_server/ic_evm_rpc
              examples/experimental/test/end_to_end/http_server/multi_deploy
              examples/experimental/test/property/candid_rpc/stable_b_tree_map
              ') }}"

              SLOW_EXCLUSIONS="${{ format('
              examples/stable/test/end_to_end/candid_rpc/bitcoin
              examples/stable/test/end_to_end/candid_rpc/stable_structures
              examples/experimental/test/end_to_end/candid_rpc/bitcoin
              examples/experimental/test/end_to_end/candid_rpc/composite_queries
              examples/experimental/test/end_to_end/candid_rpc/ckbtc
              examples/experimental/test/end_to_end/candid_rpc/cross_canister_calls
              examples/experimental/test/end_to_end/candid_rpc/management_canister
              examples/experimental/test/end_to_end/candid_rpc/stable_structures
              examples/experimental/test/end_to_end/http_server/autoreload
              examples/experimental/test/end_to_end/http_server/large_files
              examples/experimental/test/end_to_end/http_server/open_value_sharing
              ') }}"

              EXCLUDE_DIRS=""

              if [[ "${{ inputs.exclude-release-only }}" == "true" ]]; then
                  EXCLUDE_DIRS="$EXCLUDE_DIRS $RELEASE_ONLY_EXCLUSIONS"
              fi

              if [[ "${{ inputs.exclude-unstable }}" == "true" ]]; then
                  EXCLUDE_DIRS="$EXCLUDE_DIRS $UNSTABLE_EXCLUSIONS"
              fi

              if [[ "${{ inputs.exclude-slow }}" == "true" ]]; then
                  EXCLUDE_DIRS="$EXCLUDE_DIRS $SLOW_EXCLUSIONS"
              fi

              # Trim leading or trailing spaces and save the exclude-dirs in the environment
              EXCLUDE_DIRS=$(echo $EXCLUDE_DIRS | xargs)
              echo "exclude-dirs=$EXCLUDE_DIRS" >> $GITHUB_OUTPUT
