name: Auto Merge Dependabot PRs
on:
    pull_request:
        types:
            - opened
            - synchronize
            - reopened

jobs:
    check-conditions:
        runs-on: ubuntu-latest
        outputs:
            should_auto_merge: ${{ steps.set_conditions.outputs.should_auto_merge }}
        steps:
            - uses: actions/checkout@v4
              with:
                  ref: ${{ github.event.pull_request.head.ref }} # This is necessary for this job to be able to get the correct commit message from `git log`

            - name: Set conditions
              id: set_conditions
              run: |
                  COMMIT_MESSAGE=$(git log -1 --pretty=format:"%s")
                  echo "$COMMIT_MESSAGE"
                  HAS_TEMPLATE_UPDATE_COMMIT="${{ contains(github.head_ref, 'chore: update templates for dependency changes') }}"
                  echo "${{ github.actor }}"
                  IS_DEPENDABOT_ACTOR="${{ github.actor == 'dependabot[bot]' }}"
                  IS_LASTMJS_ACTOR="${{ github.actor == 'lastmjs' }}"
                  IS_DEPENDENCIES_LABEL="${{ contains(github.event.pull_request.labels.*.name, 'dependencies') }}"

                  IS_DEPENDABOT_PR_WITH_TEMPLATE_UPDATE="false"
                  if [[ "$IS_DEPENDENCIES_LABEL" == "true" && "$IS_LASTMJS_ACTOR" == "true" && "$HAS_TEMPLATE_UPDATE_COMMIT" == "true" ]]; then
                      IS_DEPENDABOT_PR_WITH_TEMPLATE_UPDATE="true"
                  else
                      IS_DEPENDABOT_PR_WITH_TEMPLATE_UPDATE="false"
                  fi

                  IS_DEPENDABOT_PR_WITHOUT_TEMPLATE_UPDATE="false"
                  if [[ "$IS_DEPENDENCIES_LABEL" == "true" && "$IS_DEPENDABOT_ACTOR" == "true" ]]; then
                      IS_DEPENDABOT_PR_WITHOUT_TEMPLATE_UPDATE="true"
                  else
                      IS_DEPENDABOT_PR_WITHOUT_TEMPLATE_UPDATE="false"
                  fi

                  SHOULD_AUTO_MERGE="false"
                  if [[ $IS_DEPENDABOT_PR_WITH_TEMPLATE_UPDATE == "true" || $IS_DEPENDABOT_PR_WITHOUT_TEMPLATE_UPDATE == "true" ]]; then
                      SHOULD_AUTO_MERGE="true"
                  fi
                  echo "should_auto_merge=$SHOULD_AUTO_MERGE" >> $GITHUB_OUTPUT

            - name: Log results for debugging
              run: |
                  echo "Commit message: $COMMIT_MESSAGE"
                  echo "Has template update commit: $HAS_TEMPLATE_UPDATE_COMMIT"
                  echo "Is dependencies label: $IS_DEPENDENCIES_LABEL"
                  echo "Is lastmjs actor: $IS_LASTMJS_ACTOR"
                  echo "Is dependabot actor: $IS_DEPENDABOT_ACTOR"
                  echo "Is dependabot PR with template update: $IS_DEPENDABOT_PR_WITH_TEMPLATE_UPDATE"
                  echo "Is dependabot PR without template update: $IS_DEPENDABOT_PR_WITHOUT_TEMPLATE_UPDATE"
                  echo "Should auto merge: $SHOULD_AUTO_MERGE"
                  echo "Should run auto merge output: ${{ steps.set_conditions.outputs.should_auto_merge }}"

    auto-merge:
        needs: check-conditions
        if: ${{ needs.check-conditions.outputs.should_auto_merge == 'true' }}
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  ref: ${{ github.event.pull_request.head.ref }}
                  token: ${{ secrets.LASTMJS_GITHUB_TOKEN }}

            - name: Approve PR
              run: gh pr review --approve "$PR_NUMBER"
              env:
                  PR_NUMBER: ${{ github.event.pull_request.number }}
                  GITHUB_TOKEN: ${{ secrets.LASTMJS_GITHUB_TOKEN }}

            - name: Merge PR
              run: |
                  gh pr merge "$PR_NUMBER" \
                      --merge \
                      --auto
              env:
                  PR_NUMBER: ${{ github.event.pull_request.number }}
                  GITHUB_TOKEN: ${{ secrets.LASTMJS_GITHUB_TOKEN }}
