name: CLI Commands

on:
    push:
        branches:
            - main
    pull_request:
        types:
            - opened
            - synchronize
            - ready_for_review
            - reopened

jobs:
    pack-azle:
        runs-on: ubuntu-latest
        steps:
            - name: Make Azle Directory
              id: make_azle_directory
              run: |
                  # Create a fresh test directory
                  AZLE_DIR="${{ github.workspace }}/azle"
                  mkdir -p "${AZLE_DIR}"
                  echo "azle_directory=${AZLE_DIR}" >> $GITHUB_OUTPUT

            - uses: actions/checkout@v4
              with:
                  path: azle

            - name: Verify that the directory is as we expect
              run: |
                  echo "Verifying the directory is as we expect"
                  ls -laR

            - uses: ./azle/.github/actions/setup_node
              with:
                  working-directory: azle

            - id: get-dfx-version
              run: |
                  PACKAGE_JSON_PATH="${{ github.workspace }}/azle/package.json"
                  DFX_VERSION=$(jq -r '.azle.globalDependencies.dfx // error("dfx version not found")' "$PACKAGE_JSON_PATH")
                  echo "dfx-version=${DFX_VERSION}" >> "$GITHUB_OUTPUT"
              shell: bash

            # Install dfx (Note: dfx must be installed before `npx azle` because the azle installation process requires dfx)
            - name: Install dfx
              uses: ./azle/.github/actions/retry_command
              with:
                  command: azle/src/stable/build/commands/dev/setup/install_dfx.sh "${{ steps.get-dfx-version.outputs.dfx-version }}"

            - run: echo "$HOME/.local/share/dfx/bin" >> $GITHUB_PATH
              shell: bash

            - uses: ./azle/.github/actions/retry_command
              with:
                  working-directory: azle
                  command: 'npm install'

            - name: Update version in package.json
              working-directory: azle
              run: |
                  # Create a unique version number using the GitHub run ID and run number
                  UNIQUE_VERSION="0.0.0-test-${GITHUB_RUN_ID}-${GITHUB_RUN_NUMBER}"
                  echo "Setting unique test version: ${UNIQUE_VERSION}"

                  # Update the version in package.json using npm version without creating a git tag
                  npm version "${UNIQUE_VERSION}" --no-git-tag-version

                  # Verify the updated version
                  UPDATED_VERSION=$(node -p "require('./package.json').version")
                  echo "Updated package.json version to: ${UPDATED_VERSION}"

                  # Save the version for later verification
                  echo "UNIQUE_VERSION=${UNIQUE_VERSION}" >> $GITHUB_ENV

            - name: Pack Azle source
              id: pack_azle
              working-directory: azle
              run: |
                  # Ensure the dist directory exists
                  mkdir -p "${{ github.workspace }}/dist"

                  # Pack into the dist directory and capture the original filename
                  ORIGINAL_PACKED_FILENAME=$(npm pack --pack-destination "${{ github.workspace }}/dist" | tail -n 1)
                  echo "Original packed filename: ${ORIGINAL_PACKED_FILENAME}"

                  # Define the final target path
                  TARGET_PACKED_FILE_PATH="${{ github.workspace }}/dist/azle.tgz"
                  echo "Target packed file path: ${TARGET_PACKED_FILE_PATH}"

                  # Construct the path to the originally created file
                  ORIGINAL_PACKED_FILE_PATH="${{ github.workspace }}/dist/${ORIGINAL_PACKED_FILENAME}"
                  echo "Original packed file path: ${ORIGINAL_PACKED_FILE_PATH}"

                  # Rename the packed file to the target name
                  mv "${ORIGINAL_PACKED_FILE_PATH}" "${TARGET_PACKED_FILE_PATH}"
                  echo "Renamed packed file to ${TARGET_PACKED_FILE_PATH}"

                  # Output the final absolute path for the installer step
                  echo "packed_file_absolute_path=${TARGET_PACKED_FILE_PATH}" >> $GITHUB_OUTPUT

            - name: Make Test Directory
              id: make_test_directory
              run: |
                  # Create a fresh test directory
                  TEST_DIR="${{ github.workspace }}/cli-test"
                  mkdir -p "${TEST_DIR}"
                  echo "test_directory=${TEST_DIR}" >> $GITHUB_OUTPUT

            - name: Install Test Azle
              working-directory: cli-test
              run: |
                  # Path to the packed azle.tgz file
                  AZLE_PACKAGE="${{ steps.pack_azle.outputs.packed_file_absolute_path }}"

                  # Temporarily install the package locally for testing
                  echo "Installing the packed azle package for testing"
                  npm install "${AZLE_PACKAGE}"

            - name: Verify that the directory is as we expect
              run: |
                  echo "Verifying the directory is as we expect"
                  ls -laR

            - name: Test Version CLI Command
              working-directory: cli-test
              run: |

                  echo "Testing version command"
                  DISPLAYED_VERSION=$(npx azle --version)
                  echo "Displayed version: ${DISPLAYED_VERSION}"

                  # Verify the version matches our unique test version
                  if [[ "${DISPLAYED_VERSION}" == *"${UNIQUE_VERSION}"* ]]; then
                    echo "✅ Verification successful: Running the correct packed version"
                  else
                    echo "❌ Verification failed: Version mismatch"
                    echo "Expected to find: ${UNIQUE_VERSION}"
                    echo "But got: ${DISPLAYED_VERSION}"
                    exit 1
                  fi

            - name: Test Dev Setup CLI Command
              working-directory: cli-test
              run: |

                  echo "Testing dev setup command"
                  npx azle dev setup

            - name: Generate Verification
              run: |
                  npx azle@latest generate ${{ github.workspace }}/azle/src/stable/lib/canisters/management/idl/ic.did > ${{ github.workspace }}/cli-test/expected_generate_output.ts

            - name: Test Generate CLI Command
              working-directory: cli-test
              run: |

                  echo "Testing generate command"
                  npx azle generate ${{ github.workspace }}/azle/src/stable/lib/canisters/management/idl/ic.did > generate_output.ts

            - name: Verify Generate Command
              working-directory: cli-test
              run: |
                  echo "Verifying generate command"
                  if ! diff expected_generate_output.ts generate_output.ts; then
                    echo "❌ Verification failed: Generated output does not match expected output"
                    exit 1
                  else
                    echo "✅ Verification successful: Generated output matches expected output"
                  fi

            # Test templates using our custom action
            - name: Test Stable Template
              uses: ./.github/actions/test_azle_template
              with:
                  template_name: 'stable_new'
                  experimental: 'false'
                  http_server: 'false'
                  working_directory: 'cli-test'
                  version: ${{ env.UNIQUE_VERSION }}

            - name: Test Experimental Template
              uses: ./.github/actions/test_azle_template
              with:
                  template_name: 'experimental_new'
                  experimental: 'true'
                  http_server: 'false'
                  working_directory: 'cli-test'
                  version: ${{ env.UNIQUE_VERSION }}

            - name: Test HTTP Server Template
              uses: ./.github/actions/test_azle_template
              with:
                  template_name: 'http_new'
                  experimental: 'true'
                  http_server: 'true'
                  working_directory: 'cli-test'
                  version: ${{ env.UNIQUE_VERSION }}
