name: Azle CLI Commands Testing

on:
    push:
        branches:
            - main
    pull_request:
        types:
            - opened
            - synchronize
            - ready_for_review
            - reopened

jobs:
    test-cli-commands-outside-azle-repo:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: ./.github/actions/setup_node

            - uses: ./.github/actions/setup_dfx

            - name: Install azle dependencies
              uses: ./.github/actions/retry_command
              with:
                  command: 'npm install'

            - name: Create unique test version
              run: |
                  # Create a unique version number using the GitHub run ID and run number
                  UNIQUE_VERSION="0.0.0-cli-test-${GITHUB_RUN_ID}-${GITHUB_RUN_NUMBER}"
                  echo "Creating unique test version: ${UNIQUE_VERSION}"

                  # Update the version in package.json using npm version without creating a git tag
                  npm version "${UNIQUE_VERSION}" --no-git-tag-version

                  # Verify the updated version
                  UPDATED_VERSION=$(jq -r '.azle.globalDependencies.node // error("node version not found")' "package.json")
                  echo "Updated package.json version to: ${UPDATED_VERSION}"

                  # Save the version for later verification
                  echo "UNIQUE_VERSION=${UNIQUE_VERSION}" >> $GITHUB_ENV

            - name: Pack azle for external testing
              id: pack_azle_source
              run: |
                  # Pack into the dist directory and capture the original filename
                  ORIGINAL_PACKED_FILENAME=$(npm pack | tail -n 1)
                  echo "Original packed filename: ${ORIGINAL_PACKED_FILENAME}"

                  # Get the absolute path by combining current directory with filename
                  ABSOLUTE_PATH="$(pwd)/${ORIGINAL_PACKED_FILENAME}"
                  echo "Absolute path: ${ABSOLUTE_PATH}"

                  # Output the final absolute path for subsequent steps
                  echo "packed_file_absolute_path=${ABSOLUTE_PATH}" >> $GITHUB_OUTPUT

            - name: Create external testing environment
              id: create_test_environment
              run: |
                  # Create a fresh test directory to simulate external user environment
                  EXTERNAL_TEST_DIR="../external_test_env"
                  mkdir -p "${EXTERNAL_TEST_DIR}"
                  echo "external_test_directory=${EXTERNAL_TEST_DIR}" >> $GITHUB_OUTPUT

            - name: Install packed azle in external environment
              working-directory: ${{ steps.create_test_environment.outputs.external_test_directory }}
              run: |
                  # Path to the packed azle.tgz file
                  AZLE_PACKAGE="${{ steps.pack_azle_source.outputs.packed_file_absolute_path }}"

                  # Install the package locally for testing
                  echo "Installing the packed azle package for CLI testing"
                  npm install "${AZLE_PACKAGE}"

            - name: Test azle version command
              working-directory: ${{ steps.create_test_environment.outputs.external_test_directory }}
              run: |
                  echo "Testing 'azle --version' command"
                  DISPLAYED_VERSION=$(npx azle --version)
                  echo "Displayed version: ${DISPLAYED_VERSION}"

                  # Verify the version matches our unique test version
                  if [[ "${DISPLAYED_VERSION}" == "${UNIQUE_VERSION}" ]]; then
                    echo "✅ Version verification successful: Running the correct packed version"
                  else
                    echo "❌ Version verification failed: Version mismatch"
                    echo "Expected to find: ${UNIQUE_VERSION}"
                    echo "But got: ${DISPLAYED_VERSION}"
                    exit 1
                  fi

            - name: Test azle dev setup command
              working-directory: ${{ steps.create_test_environment.outputs.external_test_directory }}
              run: |
                  echo "Testing 'azle dev setup' command"

                  # Read expected versions from package.json
                  echo "Reading expected versions from package.json"
                  EXPECTED_NODE_VERSION=$(jq -r '.azle.globalDependencies.node // "not found"' "${{ github.workspace }}/package.json")
                  EXPECTED_RUST_VERSION=$(jq -r '.azle.globalDependencies.rust // "not found"' "${{ github.workspace }}/package.json")
                  EXPECTED_DFX_VERSION=$(jq -r '.azle.globalDependencies.dfx // "not found"' "${{ github.workspace }}/package.json")
                  EXPECTED_WASI2IC_VERSION=$(jq -r '.azle.globalDependencies.wasi2ic // "not found"' "${{ github.workspace }}/package.json")

                  echo "Expected Node version: ${EXPECTED_NODE_VERSION}"
                  echo "Expected Rust version: ${EXPECTED_RUST_VERSION}"
                  echo "Expected dfx version: ${EXPECTED_DFX_VERSION}"
                  echo "Expected wasi2ic version: ${EXPECTED_WASI2IC_VERSION}"

                  # Run azle dev setup
                  npx azle dev setup

                  echo "Verifying installed versions match expected versions"

                  # Check Node version
                  if [[ "${EXPECTED_NODE_VERSION}" != "not found" ]]; then
                    ACTUAL_NODE_VERSION=$(node --version | sed 's/^v//')
                    echo "Actual Node version: ${ACTUAL_NODE_VERSION}"
                    if [[ "${ACTUAL_NODE_VERSION}" == "${EXPECTED_NODE_VERSION}" ]]; then
                      echo "✅ Node version verification successful"
                    else
                      echo "❌ Node version verification failed: Expected ${EXPECTED_NODE_VERSION}, got ${ACTUAL_NODE_VERSION}"
                      exit 1
                    fi
                  fi

                  # Check Rust version
                  if [[ "${EXPECTED_RUST_VERSION}" != "not found" ]]; then
                    ACTUAL_RUST_VERSION=$(rustc --version | awk '{print $2}')
                    echo "Actual Rust version: ${ACTUAL_RUST_VERSION}"
                    if [[ "${ACTUAL_RUST_VERSION}" == "${EXPECTED_RUST_VERSION}" ]]; then
                      echo "✅ Rust version verification successful"
                    else
                      echo "❌ Rust version verification failed: Expected ${EXPECTED_RUST_VERSION}, got ${ACTUAL_RUST_VERSION}"
                      exit 1
                    fi
                  fi

                  # Check dfx version
                  if [[ "${EXPECTED_DFX_VERSION}" != "not found" ]]; then
                    ACTUAL_DFX_VERSION=$(dfx --version | awk '{print $2}')
                    echo "Actual dfx version: ${ACTUAL_DFX_VERSION}"
                    if [[ "${ACTUAL_DFX_VERSION}" == "${EXPECTED_DFX_VERSION}" ]]; then
                      echo "✅ dfx version verification successful"
                    else
                      echo "❌ dfx version verification failed: Expected ${EXPECTED_DFX_VERSION}, got ${ACTUAL_DFX_VERSION}"
                      exit 1
                    fi
                  fi

                  # Check wasi2ic version
                  if [[ "${EXPECTED_WASI2IC_VERSION}" != "not found" ]]; then
                    ACTUAL_WASI2IC_VERSION=$(wasi2ic --version 2>/dev/null | head -n1 | awk '{print $NF}' || echo "not installed")
                    echo "Actual wasi2ic version: ${ACTUAL_WASI2IC_VERSION}"
                    if [[ "${ACTUAL_WASI2IC_VERSION}" == "${EXPECTED_WASI2IC_VERSION}" ]]; then
                      echo "✅ wasi2ic version verification successful"
                    else
                      echo "❌ wasi2ic version verification failed: Expected ${EXPECTED_WASI2IC_VERSION}, got ${ACTUAL_WASI2IC_VERSION}"
                      exit 1
                    fi
                  fi

                  echo "✅ All version verifications completed successfully"

            - name: Test azle dev template commands
              run: |
                  echo "Testing azle dev template commands"

                  # Helper function to clean all template files
                  clean_templates() {
                    echo "Cleaning all template files"
                    rm -f dist/canister_templates/stable.wasm
                    rm -f dist/canister_templates/experimental.wasm
                  }

                  # Helper function to check file size
                  check_file_size() {
                    local file="$1"
                    local file_size=$(stat -c%s "$file" 2>/dev/null || echo "0")
                    if [[ "$file_size" -gt 0 ]]; then
                      return 0
                    else
                      return 1
                    fi
                  }

                  # Remove existing template files to test regeneration
                  echo "Initial cleanup: Removing existing template files for regeneration test"
                  clean_templates

                  # Test azle dev template (stable)
                  echo "Testing 'azle dev template' command (stable only)"
                  npx azle dev template

                  # Verify stable template was created and has valid size
                  if [[ -f "dist/canister_templates/stable.wasm" ]]; then
                    echo "✅ Stable template file created successfully"
                    if ! check_file_size "dist/canister_templates/stable.wasm"; then
                      echo "❌ Stable template size check failed during stable-only test"
                      exit 1
                    fi
                  else
                    echo "❌ Stable template verification failed: stable.wasm was not created"
                    exit 1
                  fi

                  # Verify experimental template was NOT created
                  if [[ -f "dist/canister_templates/experimental.wasm" ]]; then
                    echo "❌ Stable command verification failed: experimental.wasm should not have been created"
                    exit 1
                  else
                    echo "✅ Stable command verification successful: experimental.wasm was correctly not created"
                  fi

                  # Clean templates for next test
                  clean_templates

                  # Test azle dev template --experimental
                  echo "Testing 'azle dev template --experimental' command (experimental only)"
                  npx azle dev template --experimental

                  # Verify experimental template was created and has valid size
                  if [[ -f "dist/canister_templates/experimental.wasm" ]]; then
                    echo "✅ Experimental template file created successfully"
                    if ! check_file_size "dist/canister_templates/experimental.wasm"; then
                      echo "❌ Experimental template size check failed during experimental-only test"
                      exit 1
                    fi
                  else
                    echo "❌ Experimental template verification failed: experimental.wasm was not created"
                    exit 1
                  fi

                  # Verify stable template was NOT created
                  if [[ -f "dist/canister_templates/stable.wasm" ]]; then
                    echo "❌ Experimental command verification failed: stable.wasm should not have been created"
                    exit 1
                  else
                    echo "✅ Experimental command verification successful: stable.wasm was correctly not created"
                  fi

                  # Clean templates for final test
                  clean_templates

                  # Test azle dev template --all
                  echo "Testing 'azle dev template --all' command (both templates)"
                  npx azle dev template --all

                  # Verify both templates were created and have valid sizes
                  STABLE_EXISTS=false
                  EXPERIMENTAL_EXISTS=false

                  if [[ -f "dist/canister_templates/stable.wasm" ]]; then
                    echo "✅ Stable template file created successfully"
                    if check_file_size "dist/canister_templates/stable.wasm"; then
                      STABLE_EXISTS=true
                    else
                      echo "❌ Stable template size check failed during --all test"
                      exit 1
                    fi
                  else
                    echo "❌ All templates verification failed: stable.wasm was not created"
                    exit 1
                  fi

                  if [[ -f "dist/canister_templates/experimental.wasm" ]]; then
                    echo "✅ Experimental template file created successfully"
                    if check_file_size "dist/canister_templates/experimental.wasm"; then
                      EXPERIMENTAL_EXISTS=true
                    else
                      echo "❌ Experimental template size check failed during --all test"
                      exit 1
                    fi
                  else
                    echo "❌ All templates verification failed: experimental.wasm was not created"
                    exit 1
                  fi

                  if [[ "$STABLE_EXISTS" == true && "$EXPERIMENTAL_EXISTS" == true ]]; then
                    echo "✅ All templates verification successful: Both stable.wasm and experimental.wasm were created with valid sizes"
                  else
                    echo "❌ All templates verification failed: Not all template files were properly created"
                    exit 1
                  fi

            - name: Test azle generate command
              working-directory: ${{ steps.create_test_environment.outputs.external_test_directory }}
              run: |
                  echo "Testing 'azle generate' command with output verification"

                  # Test the generate command with the packed version
                  echo "Running azle generate command"
                  npx azle generate ${{ github.workspace }}/src/stable/lib/canisters/management/idl/ic.did > generate_output.ts

                  # Verify the generated file exists and is not empty
                  echo "Verifying azle generate command output"
                  if [[ -f "generate_output.ts" ]]; then
                    FILE_SIZE=$(stat -c%s "generate_output.ts" 2>/dev/null || echo "0")
                    if [[ "$FILE_SIZE" -gt 0 ]]; then
                      echo "✅ Generate command verification successful: Generated file exists and has valid size ($FILE_SIZE bytes)"
                    else
                      echo "❌ Generate command verification failed: Generated file is empty (0 bytes)"
                      exit 1
                    fi
                  else
                    echo "❌ Generate command verification failed: Generated file does not exist"
                    exit 1
                  fi

            - name: Start dfx for testing new command
              working-directory: ${{ steps.create_test_environment.outputs.external_test_directory }}
              shell: bash
              run: dfx start --clean --background --artificial-delay 0

            - name: Test stable project creation with azle new command
              uses: ./.github/actions/test_azle_new
              with:
                  project_name: 'stable_project_test'
                  experimental: 'false'
                  http_server: 'false'
                  working_directory: ${{ steps.create_test_environment.outputs.external_test_directory }}
                  version: ${{ env.UNIQUE_VERSION }}
                  packed_file_path: ${{ steps.pack_azle_source.outputs.packed_file_absolute_path }}

            - name: Test experimental project creation with azle new command
              uses: ./.github/actions/test_azle_new
              with:
                  project_name: 'experimental_project_test'
                  experimental: 'true'
                  http_server: 'false'
                  working_directory: ${{ steps.create_test_environment.outputs.external_test_directory }}
                  version: ${{ env.UNIQUE_VERSION }}
                  packed_file_path: ${{ steps.pack_azle_source.outputs.packed_file_absolute_path }}

            - name: Test HTTP server project creation with azle new command
              uses: ./.github/actions/test_azle_new
              with:
                  project_name: 'http_server_project_test'
                  experimental: 'true'
                  http_server: 'true'
                  working_directory: ${{ steps.create_test_environment.outputs.external_test_directory }}
                  version: ${{ env.UNIQUE_VERSION }}
                  packed_file_path: ${{ steps.pack_azle_source.outputs.packed_file_absolute_path }}
