name: Release Branch Workflow

on:
    pull_request: # Runs on pull requests to any branch
        branches:
            - release--*

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - run: echo "Hello world! with wild cards"
