name: Release Branch Workflow

on:
    pull_request:
        # Sequence of patterns matched against refs/heads
        branches:
            - 'releases/**'
            - 'release--**'

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - run: echo "Hello world! with wild cards"
