name: Release Branch Workflow

on:
    push:
        branches:
            - release--*
    pull_request: # Runs on pull requests to any branch

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - run: echo "Hello world! with wild cards"
