name: Release Branch Workflow

on:
    pull_request:
        branches:
            - 'release/bdemann.tests.release'

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - run: echo "Hello world! with wild cards"
