name: 'Copilot Setup Steps'

# Allow testing of the setup steps from your repository's "Actions" tab.
on: workflow_dispatch

jobs:
    # The job MUST be called `copilot-setup-steps` or it will not be picked up by Copilot.
    copilot-setup-steps:
        runs-on: ubuntu-latest

        # Set the permissions to the lowest permissions possible needed for your steps.
        # Copilot will be given its own token for its operations.
        permissions:
            # If you want to clone the repository as part of your setup steps, for example to install dependencies, you'll need the `contents: read` permission. If you don't clone the repository in your setup steps, Copilot will do this for you automatically after the steps complete.
            contents: read

        # You can define any steps you want, and they will run before the agent starts.
        # If you do not check out your code, Copilot will do this for you.
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - uses: ./.github/actions/setup_node

            - uses: ./.github/actions/setup_dfx

            - uses: ./.github/actions/retry_command
              with:
                  command: 'npm install'

            - name: Install global dependencies
              run: |
                  AZLE_VERBOSE=true npx azle dev setup --rust --wasi2ic

            - name: Start dfx with artificial delay 0
              run: dfx start --clean --background --artificial-delay 0

            - name: Ensure clean slate by running one test
              run: |
                  npm install
                  npm link
                  cd examples/stable/test/end_to_end/candid_rpc/async_await
                  npm install
                  npm link azle
                  AZLE_VERBOSE=true AZLE_DEV_TEMPLATE=true npm test
