name: Create Branch Prefix
on:
    workflow_call:
        inputs:
            prefix:
                required: true
                type: string
                description: 'Prefix to use for branch names (e.g. benchmark, release)'
            version:
                required: true
                type: string
                description: 'Version to use in branch names'
        outputs:
            branch-prefix:
                description: 'The generated branch prefix ({prefix}--{version}-)'
                value: ${{ jobs.create-branch-prefix.outputs.branch-prefix }}
            base-branch:
                description: 'The generated base branch name ({prefix}--{version})'
                value: ${{ jobs.create-branch-prefix.outputs.base-branch }}
        secrets:
            AZLE_BOT_KEY:
                required: true

permissions:
    contents: read

jobs:
    create-branch-prefix:
        name: Create Branch and Branch Prefix
        runs-on: ubuntu-latest
        permissions:
            contents: write
        outputs:
            branch-prefix: ${{ steps.create-prefix.outputs.branch-prefix }}
            base-branch: ${{ steps.create-prefix.outputs.base-branch }}
        steps:
            - name: Generate GitHub App Token
              id: github-app-auth
              uses: actions/create-github-app-token@v1
              with:
                  app-id: ${{ vars.AZLE_BOT_ID }}
                  private-key: ${{ secrets.AZLE_BOT_KEY }}

            - uses: actions/checkout@v4
              with:
                  ref: ${{ github.ref }}
                  token: ${{ steps.github-app-auth.outputs.token }}

            - id: create-prefix
              shell: bash
              run: |
                  VERSION="${{ inputs.version }}"
                  echo "branch-prefix=${{ inputs.prefix }}--$VERSION--" >> $GITHUB_OUTPUT
                  echo "base-branch=${{ inputs.prefix }}--$VERSION" >> $GITHUB_OUTPUT

            - uses: ./.github/actions/configure_git

            - name: Create base branch
              run: git checkout -b ${{ steps.create-prefix.outputs.base-branch }}

            - run: git push origin ${{ steps.create-prefix.outputs.base-branch }}
