name: Create Branch Prefix
on:
    workflow_call:
        inputs:
            prefix:
                required: true
                type: string
                description: 'Prefix to use for branch names (e.g. benchmark, release)'
            version:
                required: true
                type: string
                description: 'Version to use in branch names'
        outputs:
            branch-prefix:
                description: 'The generated branch prefix ({prefix}--{version}-)'
                value: ${{ jobs.create-branch-prefix.outputs.branch-prefix }}
            base-branch:
                description: 'The generated base branch name ({prefix}--{version})'
                value: ${{ jobs.create-branch-prefix.outputs.base-branch }}
        secrets:
            GPG_SIGNING_KEY:
                required: true

jobs:
    create-branch-prefix:
        name: Create Branch and Branch Prefix
        runs-on: ubuntu-latest
        outputs:
            branch-prefix: ${{ steps.create-prefix.outputs.branch-prefix }}
            base-branch: ${{ steps.create-prefix.outputs.base-branch }}
        steps:
            - uses: actions/checkout@v4
              with:
                  ref: ${{ github.ref }}

            - id: create-prefix
              shell: bash
              run: |
                  VERSION="${{ inputs.version }}"
                  echo "branch-prefix=${{ inputs.prefix }}--$VERSION-" >> $GITHUB_OUTPUT
                  echo "base-branch=${{ inputs.prefix }}--$VERSION" >> $GITHUB_OUTPUT

            - uses: ./.github/actions/configure_git
              with:
                  gpg_signing_key: ${{ secrets.GPG_SIGNING_KEY }}
                  signing_key_id: C8B77BCBE16CD2B94B43F9C8757397B82D4ED7B0

            - name: Create base branch
              run: git checkout -b ${{ steps.create-prefix.outputs.base-branch }}

            - run: git push origin ${{ steps.create-prefix.outputs.base-branch }}
