name: Example/test maintenance (package-lock updating, formatting, linting)
on:
    workflow_dispatch:
        inputs:
            delete_package_lock:
                description: 'Delete package-lock.json files before npm install'
                required: false
                default: false
                type: boolean
    schedule:
        # Run at 10:00 UTC (4:00 AM MT) every day
        - cron: '0 10 * * *'

permissions:
    contents: read

jobs:
    determine-prefix:
        runs-on: ubuntu-latest
        outputs:
            prefix: ${{ steps.set-prefix.outputs.prefix }}
        steps:
            - id: set-prefix
              run: echo "prefix=maintenance-$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

    create-branch-prefix:
        needs:
            - determine-prefix
        permissions:
            contents: write
        uses: ./.github/workflows/create_branch_prefix.yml
        with:
            prefix: ${{ needs.determine-prefix.outputs.prefix }}
            version: $(jq -r '.version' package.json)

    prepare-maintenance:
        name: Prepare Maintenance
        needs:
            - create-branch-prefix
        runs-on: ubuntu-latest
        permissions:
            contents: write
        outputs:
            test-infos: ${{ steps.get-test-infos.outputs.test-infos }}
        steps:
            - uses: actions/checkout@v4
              with:
                  ref: ${{ needs.create-branch-prefix.outputs.base-branch }}
                  token: ${{ secrets.GITHUB_TOKEN }}

            - uses: ./.github/actions/setup_node

            - uses: ./.github/actions/setup_dfx

            - uses: ./.github/actions/retry_command
              with:
                  command: 'npm install'

            # Conditionally delete and update workspace package-lock.json
            - name: Delete workspace package-lock.json
              if: ${{ github.event.inputs.delete_package_lock == 'true' }}
              run: if [ -f package-lock.json ]; then rm package-lock.json; fi
              working-directory: ./examples

            - name: Update workspace dependencies
              uses: ./.github/actions/retry_command
              with:
                  command: 'npm install'
                  working-directory: ${{ github.workspace }}/examples

            # Run global prettier/lint fixes
            - name: Run Prettier
              run: npx prettier --write .

            - name: Run ESLint
              run: npx eslint . --fix

            - name: Create GraphQL mutation file
              run: |
                  mkdir -p .github/api
                  cat > .github/api/createCommitOnBranch.gql << 'EOF'
                  mutation (
                      $githubRepository: String!,
                      $branchName: String!,
                      $expectedHeadOid: GitObjectID!
                      $commitMessage: String!
                      $files: [FileAddition!]!
                  ) {
                    createCommitOnBranch(
                      input: {
                      branch:
                      {
                          repositoryNameWithOwner: $githubRepository,
                          branchName: $branchName
                      },
                      message: {headline: $commitMessage},
                      fileChanges: {
                          additions: $files
                      }
                      expectedHeadOid: $expectedHeadOid
                      }
                    ){
                      commit {
                      url
                      }
                    }
                  }
                  EOF

            - name: Commit formatting and linting changes via GraphQL
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  # Check if there are any changes to commit
                  if git diff --quiet; then
                    echo "No changes to commit"
                    exit 0
                  fi

                  # Get all changed files
                  CHANGED_FILES=($(git diff --name-only))

                  if [ ${#CHANGED_FILES[@]} -eq 0 ]; then
                    echo "No files to commit"
                    exit 0
                  fi

                  echo "Committing ${#CHANGED_FILES[@]} files via GraphQL API..."

                  # Create temporary directory for base64 files
                  TEMP_DIR=$(mktemp -d)
                  trap "rm -rf $TEMP_DIR" EXIT

                  # Build files parameter using temporary files
                  FILES=""
                  counter=0
                  for file in "${CHANGED_FILES[@]}"; do
                    echo "Processing file: $file"

                    # Create temporary file for base64 content
                    temp_file="$TEMP_DIR/file_${counter}.b64"
                    base64 -w0 "$file" > "$temp_file"

                    FILES="${FILES} -F files[][path]=$file -F files[][contents]=@$temp_file"
                    counter=$((counter + 1))
                  done

                  # Get current HEAD commit
                  EXPECTED_HEAD_OID=$(git rev-parse HEAD)
                  CURRENT_BRANCH=$(git branch --show-current)

                  # Create commit via GraphQL API (automatically signed)
                  gh api graphql \
                    -F githubRepository="${GITHUB_REPOSITORY}" \
                    -F branchName="$CURRENT_BRANCH" \
                    -F expectedHeadOid="$EXPECTED_HEAD_OID" \
                    -F commitMessage="Example/test maintenance: formatting and linting" \
                    -F "query=@.github/api/createCommitOnBranch.gql" \
                    ${FILES}

            - id: get-test-infos
              uses: ./.github/actions/get_test_infos
              with:
                  directories: ${{ github.workspace }}/examples

    update-test-dependencies:
        needs:
            - prepare-maintenance
            - create-branch-prefix
        name: Update dependencies for ${{ matrix.test.name }}
        runs-on: ubuntu-latest
        permissions:
            contents: write
        strategy:
            fail-fast: false
            matrix:
                test: ${{ fromJson(needs.prepare-maintenance.outputs.test-infos) }}
        steps:
            - uses: actions/checkout@v4
              with:
                  ref: ${{ needs.create-branch-prefix.outputs.base-branch }}
                  token: ${{ secrets.GITHUB_TOKEN }}

            - uses: ./.github/actions/setup_node

            - uses: ./.github/actions/setup_dfx

            - name: Install azle dependencies
              uses: ./.github/actions/retry_command
              with:
                  command: 'npm install'

            # Install dependencies at the examples workspace root
            - name: Install workspace dependencies
              uses: ./.github/actions/retry_command
              with:
                  command: 'npm install'
                  working-directory: ${{ github.workspace }}/examples

            # Conditionally delete package-lock.json if input is true
            - name: Delete package-lock.json
              if: ${{ github.event.inputs.delete_package_lock == 'true' }}
              run: if [ -f package-lock.json ]; then rm package-lock.json; fi
              working-directory: ${{ matrix.test.path }}

            # Update package-lock.json in test directory
            - name: Update package-lock.json
              uses: ./.github/actions/retry_command
              with:
                  command: 'npm install'
                  working-directory: ${{ matrix.test.path }}

            - name: Create branch name
              id: create-branch-name
              uses: ./.github/actions/create_branch_name
              with:
                  prefix: ${{ needs.create-branch-prefix.outputs.branch-prefix }}
                  path: ${{ matrix.test.displayPath }}

            - name: Create branch and commit changes via GraphQL
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  BRANCH_NAME="${{ steps.create-branch-name.outputs.branch-name }}"

                  # Create new branch
                  git checkout -b "$BRANCH_NAME"

                  # Check if there are any changes to commit
                  if git diff --quiet; then
                    echo "No changes to commit"
                    exit 0
                  fi

                  # Get all changed files
                  CHANGED_FILES=($(git diff --name-only))

                  if [ ${#CHANGED_FILES[@]} -eq 0 ]; then
                    echo "No files to commit"
                    exit 0
                  fi

                  echo "Committing ${#CHANGED_FILES[@]} files via GraphQL API..."

                  # Create temporary directory for base64 files
                  TEMP_DIR=$(mktemp -d)
                  trap "rm -rf $TEMP_DIR" EXIT

                  # Build files parameter using temporary files
                  FILES=""
                  counter=0
                  for file in "${CHANGED_FILES[@]}"; do
                    echo "Processing file: $file"

                    # Create temporary file for base64 content
                    temp_file="$TEMP_DIR/file_${counter}.b64"
                    base64 -w0 "$file" > "$temp_file"

                    FILES="${FILES} -F files[][path]=$file -F files[][contents]=@$temp_file"
                    counter=$((counter + 1))
                  done

                  # Get current HEAD commit and push branch first
                  git push origin "$BRANCH_NAME"
                  EXPECTED_HEAD_OID=$(git rev-parse HEAD)

                  # Create commit via GraphQL API (automatically signed)
                  gh api graphql \
                    -F githubRepository="${GITHUB_REPOSITORY}" \
                    -F branchName="$BRANCH_NAME" \
                    -F expectedHeadOid="$EXPECTED_HEAD_OID" \
                    -F commitMessage="Example/test maintenance: update dependencies" \
                    -F "query=@.github/api/createCommitOnBranch.gql" \
                    ${FILES}

    squash-branches:
        permissions:
            contents: write
        needs:
            - update-test-dependencies
            - create-branch-prefix
        uses: ./.github/workflows/squash_branches.yml
        with:
            base-branch: ${{ needs.create-branch-prefix.outputs.base-branch }}
            branch-prefix: ${{ needs.create-branch-prefix.outputs.branch-prefix }}
            commit-message: 'Example/test maintenance: update dependencies'

    create-pr:
        needs:
            - squash-branches
            - create-branch-prefix
        runs-on: ubuntu-latest
        permissions:
            contents: read
            pull-requests: write
        steps:
            - uses: actions/checkout@v4
              with:
                  ref: ${{ github.ref }}
                  fetch-depth: 0

            - name: Check for differences
              id: check-diff
              run: |
                  git fetch origin main
                  if git diff --quiet origin/main ${{ needs.create-branch-prefix.outputs.base-branch }}; then
                    echo "No differences found between branches"
                    echo "has_changes=false" >> $GITHUB_OUTPUT
                  else
                    echo "Changes detected"
                    echo "has_changes=true" >> $GITHUB_OUTPUT
                  fi

            - name: Create Pull Request
              if: steps.check-diff.outputs.has_changes == 'true'
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  gh pr create \
                    --base main \
                    --head ${{ needs.create-branch-prefix.outputs.base-branch }} \
                    --title "Example/test maintenance: update dependencies, formatting, and linting" \
                    --body "Automated PR for maintenance tasks:
                    - Updated package-lock.json files
                    - Fixed formatting with Prettier
                    - Fixed linting issues with ESLint"
