name: Run Benchmarks on Release Merge

on:
    push:
        branches:
            - main

permissions:
    contents: read

jobs:
    determine-context:
        name: Determine Workflow Context
        runs-on: ubuntu-latest
        outputs:
            should-run: ${{ steps.workflow-context.outputs.is_main_branch_push_from_release_merge }}
        steps:
            - uses: actions/checkout@v4
            - uses: ./.github/actions/determine_workflow_context
              id: workflow-context

    run-benchmarks:
        name: Run Benchmarks
        needs: determine-context
        permissions:
            contents: write
        if: needs.determine-context.outputs.should-run == 'true'
        uses: ./.github/workflows/benchmark.yml
        with:
            exclude-slow-benchmarks: false
            exclude-unstable-benchmarks: false
            exclude-release-only-benchmarks: false
        secrets:
            AZLE_BOT_KEY: ${{ secrets.AZLE_BOT_KEY }}
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
