name: Squash Branches
on:
    workflow_call:
        inputs:
            base-branch:
                required: true
                type: string
            branch-prefix:
                required: true
                type: string
            commit-message:
                required: true
                type: string
        secrets:
            AZLE_BOT_KEY:
                required: true
            GH_TOKEN:
                required: true

permissions:
    contents: read

jobs:
    squash:
        name: Squash Branches
        runs-on: ubuntu-latest
        env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        steps:
            - name: Generate GitHub App Token
              id: github-app-auth
              uses: actions/create-github-app-token@v1
              with:
                  app-id: ${{ vars.AZLE_BOT_ID }}
                  private-key: ${{ secrets.AZLE_BOT_KEY }}

            - uses: actions/checkout@v4
              with:
                  ref: ${{ inputs.base-branch }}
                  token: ${{ steps.github-app-auth.outputs.token }}
                  fetch-depth: 0

            - name: Collect branches
              id: collect-branches
              run: |
                  # Get branches and convert to space-separated list
                  BRANCHES=$(git branch -r | grep "origin/${{ inputs.branch-prefix }}" | sed 's/origin\///' | xargs)
                  echo "branches=$BRANCHES" >> $GITHUB_OUTPUT

            - name: Display collected branches
              run: |
                  echo "Collected branches:"
                  for branch in ${{ steps.collect-branches.outputs.branches }}; do
                    echo "  - $branch"
                  done
                  echo "End of branch list"

            - name: Fetch branches
              run: |
                  echo "Fetching all branches..."
                  BRANCHES_TO_FETCH=""
                  for branch in ${{ steps.collect-branches.outputs.branches }}; do
                    BRANCHES_TO_FETCH+=" $branch:$branch"
                  done
                  git fetch origin $BRANCHES_TO_FETCH

            - name: Squash changes
              env:
                  GITHUB_TOKEN: ${{ steps.github-app-auth.outputs.token }}
              run: |
                  CURRENT_BRANCH=$(git branch --show-current)
                  REPO="${GITHUB_REPOSITORY}"

                  for branch in ${{ steps.collect-branches.outputs.branches }}; do
                    echo "Merging $branch into $CURRENT_BRANCH"
                    git merge --squash $branch
                  done

                  # Check if there are any changes to commit
                  if git diff --staged --quiet; then
                    echo "No changes to commit"
                  else
                    # Stage all changes for commit via API
                    git add -A
                    CHANGED=$(git diff --cached --name-only)

                    if [ -n "$CHANGED" ]; then
                      # Get current branch HEAD for expectedHeadOid
                      EXPECTED_HEAD=$(gh api repos/$REPO/git/ref/heads/$CURRENT_BRANCH --jq .object.sha)

                      # Build GraphQL payload for commit
                      tmp=$(mktemp)
                      cat > "$tmp" << 'GRAPHQL_START'
                  {"query":"mutation($input:CreateCommitOnBranchInput!){createCommitOnBranch(input:$input){commit{oid url}}}","variables":{"input":{"branch":{"repositoryNameWithOwner":"
                  GRAPHQL_START

                      echo -n "$REPO" >> "$tmp"
                      cat >> "$tmp" << 'GRAPHQL_MID'
                  ","branchName":"
                  GRAPHQL_MID

                      echo -n "$CURRENT_BRANCH" >> "$tmp"
                      cat >> "$tmp" << 'GRAPHQL_FILES'
                  "},"fileChanges":{"additions":[
                  GRAPHQL_FILES

                      first=true
                      while IFS= read -r f; do
                        content=$(base64 -w0 "$f")
                        if [ "$first" = true ]; then
                          first=false
                        else
                          echo "," >> "$tmp"
                        fi
                        echo -n "{\"path\":\"$f\",\"contents\":\"$content\"}" >> "$tmp"
                      done <<< "$CHANGED"

                      # Close additions, add commit message and expectedHeadOid
                      cat >> "$tmp" << 'GRAPHQL_END'
                  ]},"message":{"headline":"
                  GRAPHQL_END

                      echo -n "${{ inputs.commit-message }}" >> "$tmp"
                      cat >> "$tmp" << 'GRAPHQL_FINAL'
                  "},"expectedHeadOid":"
                  GRAPHQL_FINAL

                      echo -n "$EXPECTED_HEAD" >> "$tmp"
                      echo '"}}}' >> "$tmp"

                      # Execute GraphQL commit using GitHub API
                      echo "Creating commit via GitHub API for branch $CURRENT_BRANCH"
                      gh api graphql --input="$tmp" | jq

                      # Cleanup temp file
                      rm -f "$tmp"
                    fi
                  fi

            - name: Delete branches
              run: |
                  if [[ -n "$(echo ${{ steps.collect-branches.outputs.branches }} | tr -d '[:space:]')" ]]; then
                      echo "Starting branch deletion process..."
                      git push origin --delete ${{ steps.collect-branches.outputs.branches }}
                  else
                      echo "No branches to delete"
                  fi
