name: 'Determine workflow context'
description: 'Determines the workflow context based on the current GitHub context'
outputs:
    is_main_branch_push_from_feature_merge:
        description: 'True if this is a push to the main branch (excluding merges from release branches)'
        value: ${{ steps.workflow-context.outputs.is_main_branch_push_from_feature_merge }}
    is_main_branch_push_from_release_merge:
        description: 'True if this is a push to the main branch from a release branch merge'
        value: ${{ steps.workflow-context.outputs.is_main_branch_push_from_release_merge }}
    is_release_branch_pr:
        description: 'True if this is a pull request from a release branch'
        value: ${{ steps.workflow-context.outputs.is_release_branch_pr }}
    is_feature_branch_pr:
        description: 'True if this is a pull request from a feature branch (non-draft)'
        value: ${{ steps.workflow-context.outputs.is_feature_branch_pr }}
    is_feature_branch_draft_pr:
        description: 'True if this is a draft pull request from a feature branch'
        value: ${{ steps.workflow-context.outputs.is_feature_branch_draft_pr }}
runs:
    using: 'composite'
    steps:
        - id: workflow-context
          run: |
              # Define conditions using shell variables
              AZLE_IS_MAIN_BRANCH_PUSH_FROM_FEATURE_MERGE=${{ github.ref == 'refs/heads/main' && !contains(github.event.head_commit.message, 'demergent-labs/release--') }}
              AZLE_IS_MAIN_BRANCH_PUSH_FROM_RELEASE_MERGE=${{ github.ref == 'refs/heads/main' && contains(github.event.head_commit.message, 'demergent-labs/release--') }}
              AZLE_IS_RELEASE_BRANCH_PR=${{ startsWith(github.head_ref, 'release--') }}
              AZLE_IS_FEATURE_BRANCH_PR=${{ !startsWith(github.head_ref, 'release--') && github.ref != 'refs/heads/main' && github.event.pull_request.draft == false }}
              AZLE_IS_FEATURE_BRANCH_DRAFT_PR=${{ !startsWith(github.head_ref, 'release--') && github.ref != 'refs/heads/main' && github.event.pull_request.draft == true }}

              # Set individual outputs
              echo "is_main_branch_push_from_feature_merge=$AZLE_IS_MAIN_BRANCH_PUSH_FROM_FEATURE_MERGE" >> $GITHUB_OUTPUT
              echo "is_main_branch_push_from_release_merge=$AZLE_IS_MAIN_BRANCH_PUSH_FROM_RELEASE_MERGE" >> $GITHUB_OUTPUT
              echo "is_release_branch_pr=$AZLE_IS_RELEASE_BRANCH_PR" >> $GITHUB_OUTPUT
              echo "is_feature_branch_pr=$AZLE_IS_FEATURE_BRANCH_PR" >> $GITHUB_OUTPUT
              echo "is_feature_branch_draft_pr=$AZLE_IS_FEATURE_BRANCH_DRAFT_PR" >> $GITHUB_OUTPUT
          shell: bash
